'use client';

import { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type Language = 'en' | 'it';
type TranslationValues = Record<string, string | number>;

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, values?: TranslationValues) => string;
}

const en: Record<string, string> = {
  dashboard: 'Dashboard', users: 'Users', sellers: 'Sellers', products: 'Products', warehouse: 'Warehouse',
  boostCampaigns: 'Boost Campaigns', orders: 'Orders', categories: 'Categories', coupons: 'Coupons',
  analytics: 'Analytics', settings: 'Settings', activityLogs: 'Activity Logs', points: 'Points', messages: 'Messages',
  storeReports: 'Store Reports', storeBanners: 'Store Banners', adminPanel: 'Admin Panel', opticalMarketplace: 'Optical Marketplace',
  logout: 'Logout', admin: 'Admin', language: 'Language', close: 'Close', cancel: 'Cancel', save: 'Save', retry: 'Retry',
  search: 'Search', view: 'View', details: 'Details', actions: 'Actions', edit: 'Edit', delete: 'Delete', approve: 'Approve', reject: 'Reject',
  block: 'Block', unblock: 'Unblock', active: 'Active', inactive: 'Inactive', pending: 'Pending', blocked: 'Blocked', ok: 'OK',
  noResults: 'No results found.', loading: 'Loading…', previous: 'Previous', next: 'Next', pageOf: 'Page {{page}} of {{last}}',
  loginTitle: 'Admin Panel', loginSubtitle: 'Sign in to your account', email: 'Email', password: 'Password', loginFailed: 'Login failed. Please check your credentials.', signingIn: 'Signing in…', signIn: 'Sign In',
  dashboardWelcome: 'Welcome to the admin panel', dashboardLoadFailed: 'Could not load dashboard statistics. Check your connection and API configuration.', totalUsers: 'Total Users', totalSellers: 'Total Sellers', totalProducts: 'Total Products', totalRevenue: 'Total Revenue', recentOrders: 'Recent Orders', noRecentOrders: 'No recent orders',
  referralProgram: 'Referral Program', referralDescription: 'Trace acquisition, campaign funding, Buyer Wallet credits, Seller Wallet ledger entries and platform costs.', exportFinancialReport: 'Export financial report', referralOverview: 'Overview', referralCampaigns: 'Campaigns', referralRewards: 'Rewards', referralAudit: 'Audit', referralAuditLog: 'Referral audit log', noReferralAudit: 'No referral audit records yet.', noReason: 'No reason recorded',
  platformReferralSettings: 'Platform referral settings', referralSettingsDescription: 'These settings govern platform-funded rewards. Seller campaigns retain their own budgets and scopes.', enablePlatformReferral: 'Enable platform referral program', requireSellerApproval: 'Require Admin approval for seller campaigns', allowExistingBuyers: 'Allow existing buyers in seller campaigns', allowStacking: 'Allow seller + platform stacking', requireEmail: 'Require verified email before rewarding', requirePhone: 'Require verified phone before rewarding', rewardType: 'Platform reward type', fixedEur: 'Fixed EUR', percentage: 'Percentage', rewardAmount: 'Platform reward amount', maxReward: 'Maximum platform reward per order', minOrder: 'Minimum qualifying product subtotal', attributionDays: 'Attribution period in days', waitingDays: 'Delivery / return protection days', monthlyLimit: 'Platform monthly reward limit', buyerLimit: 'Platform per-buyer limit', saveReferralSettings: 'Save referral settings', saving: 'Saving…', all: 'All', filterStatus: 'Filter status', noCampaigns: 'No seller referral campaigns.', noRewards: 'No referral rewards for this filter.', sellerReferralCampaign: 'Seller referral campaign', reward: 'Reward', source: 'Source', order: 'Order', eligibleSubtotal: 'Eligible subtotal', trace: 'Trace', buyerTransaction: 'Buyer transaction', sellerLedger: 'Seller ledger', platformLedger: 'Platform ledger', reversal: 'Reversal', manualApprove: 'Manual approve', suspend: 'Suspend', reverse: 'Reverse', paid: 'paid', reserved: 'reserved', clicks: 'clicks', campaignStatus: 'Campaign status', approvalStatus: 'Approval status', reasonForAction: 'Reason for action',
  marketplaceFinance: 'Marketplace Finance', financeDescription: 'Buyer payments, seller balances, reversals and bank payout records. Updates every 5 seconds.', sellerBalances: 'Seller balances', sellerLedgerFinance: 'Seller ledger', boostAdsRevenue: 'Boost Ads revenue', withdrawals: 'Withdrawals', buyerWalletTransactions: 'Buyer wallet transactions', buyerIdFilter: 'Buyer ID filter', noFinancialRecords: 'No records on this page.', unableLoadFinance: 'Unable to load financial records.', available: 'Available', reservedForAds: 'Reserved for ads', adSpend: 'Ad spend', walletTopUps: 'Wallet top-ups', pendingEarnings: 'Pending earnings', reservedWithdrawal: 'Reserved withdrawal', disputed: 'Disputed', refundDebt: 'Refund debt', totalEarningsAfterReversals: 'Total earnings after reversals', method: 'Method', legacy: 'legacy', shipment: 'Shipment', withdrawal: 'Withdrawal', boostCampaign: 'Boost campaign', ledgerChanges: 'Ledger changes and resulting balances', payoutReference: 'Payout reference', notRecorded: 'Not recorded', bankTransferHelp: 'Process the bank transfer through your payout system. Record completion only after it succeeds.', withdrawalAction: 'Withdrawal action', selectAction: 'Select action', withdrawalNotes: 'Review / payout notes', bankPayoutReference: 'Completed bank payout reference', applyWithdrawal: 'Apply withdrawal action', unableUpdateWithdrawal: 'Could not update withdrawal.',
  userDetails: 'User details', userNotFound: 'User not found', profile: 'Profile', phone: 'Phone', created: 'Created', emailVerified: 'Email verified', blockAccount: 'Block account', unblockAccount: 'Unblock account', cannotBlockSelf: 'You cannot change block status on your own account.', failedUpdateUser: 'Failed to update user', userBlocked: 'User blocked', userUnblocked: 'User unblocked', manageUsers: 'Create, block, and remove buyers, sellers, and admins', createUser: 'Create User', editUser: 'Edit User', update: 'Update', searchUsers: 'Search users…', allRoles: 'All roles', buyer: 'Buyer', seller: 'Seller', allAccess: 'All access', notBlocked: 'Not blocked', name: 'Name', role: 'Role', access: 'Access', newPassword: 'New password (leave empty to keep current)', userCreated: 'User created successfully', userUpdated: 'User updated successfully', userDeleted: 'User deleted successfully', failedLoadUsers: 'Could not load users. Check your connection and try again.', failedSaveUser: 'Failed to save user', failedDeleteUser: 'Failed to delete user', cannotDeleteSelf: 'You cannot delete your own account from here.',
  manageSellers: 'Manage sellers and stores', searchSellers: 'Search sellers…', storeName: 'Store Name', owner: 'Owner', storeDetails: 'Store Details', sellerNotFound: 'Seller not found', storeApproved: 'Store approved successfully', storeRejected: 'Store rejected successfully', failedLoadSellers: 'Failed to load sellers', failedApproveStore: 'Failed to approve store', failedRejectStore: 'Failed to reject store', rejectionReason: 'Rejection reason:',
  manageProducts: 'Manage all products', searchProducts: 'Search products…', product: 'Product', sku: 'SKU', store: 'Store', category: 'Category', price: 'Price', status: 'Status', approved: 'Approved', productDetails: 'Product Details', productNotFound: 'Product not found', productApproved: 'Product approved successfully', productRejected: 'Product rejected successfully', productDeleted: 'Product deleted successfully', failedLoadProducts: 'Failed to load products', failedApproveProduct: 'Failed to approve product', failedRejectProduct: 'Failed to reject product', failedDeleteProduct: 'Failed to delete product', confirmDeleteProduct: 'Are you sure you want to delete this product?', viewProduct: 'View',
  warehouseTitle: 'Warehouse', warehouseDescription: 'Manage wholesale stock, seller orders, categories and availability.', addStockProduct: 'Add Stock Product', productListings: 'Product listings', warehouseOrders: 'Warehouse orders', warehouseCategories: 'Categories', loadingInventory: 'Loading warehouse inventory…', noWarehouseProducts: 'No warehouse products match these filters.', warehouseStockProduct: 'Warehouse stock product', availability: 'Availability', inStock: 'In stock', lowStock: 'Low stock', outOfStock: 'Out of stock', addWarehouseProduct: 'Add warehouse product', editWarehouseProduct: 'Edit warehouse product', wholesaleOnly: 'Wholesale stock only. Prescription fields are intentionally not available.', selectCategory: 'Select category', productImage: 'Product image', productName: 'Product name', unitPrice: 'Unit price (€)', shippingFee: 'Shipping fee (€)', availableQuantity: 'Available quantity', lowStockAlert: 'Low stock alert at', color: 'Color', templeSize: 'Temple / arm size', lensSize: 'Lens size', bridgeSize: 'Bridge size', brand: 'Brand', lensMaterial: 'Lens material', replacementFrequency: 'Replacement frequency', packSize: 'Pack size', baseCurve: 'Base curve', diameter: 'Diameter', waterContent: 'Water content', solutionType: 'Solution type', volume: 'Volume / ml', packType: 'Pack type', expiryDate: 'Expiry date', description: 'Description', availableToSellers: 'Available to sellers', saveProduct: 'Save Product', saveCategory: 'Save Category', editWarehouseCategory: 'Edit Warehouse Category', addWarehouseCategory: 'Add Warehouse Category', productType: 'Product type', archive: 'Archive', warehouseProductSaved: 'Warehouse product {{action}} successfully.', archiveWarehouseProduct: 'Archive this warehouse product?', warehouseProductArchived: 'Warehouse product archived.', warehouseCategoryArchived: 'Warehouse category archived.', warehouseOrderUpdated: 'Warehouse order updated.', warehouseOrder: 'Warehouse order', subtotal: 'Subtotal', shipping: 'Shipping', paidFromSellerWallet: 'Paid from Seller Wallet', units: 'units', orderStatus: 'Order status', shippingCarrier: 'Shipping carrier', trackingNumber: 'Tracking number', shippingNotes: 'Shipping notes', saveOrder: 'Save order', cancellingPaidOrder: 'Cancelling a paid warehouse order refunds its total to the seller wallet. This cannot be undone.',
  boostTitle: 'Boost campaigns', boostDescription: 'Review product advertising, reserved funds, performance and audit history.', administration: 'Administration', campaignControl: 'Discount Campaign Control', bannerReview: 'Promotional Banner Review', campaignReviewDescription: 'Review scheduled campaigns, inspect history and performance, and take controlled lifecycle actions.', searchCampaigns: 'Search campaigns', allStatuses: 'All statuses', allPayments: 'All payments', allApprovals: 'All approvals', allPlacements: 'All placements', sellerId: 'Seller ID', productId: 'Product ID', startsFrom: 'Starts from', startsThrough: 'Starts through', applyFilters: 'Apply filters', campaignProduct: 'Campaign / product', statusPayment: 'Status / payment', dates: 'Dates', budgetRemaining: 'Budget / remaining', spend: 'Spend', impressions: 'Impressions', clicksCtr: 'Clicks / CTR', cpc: 'CPC', conversionsRevenue: 'Conversions / revenue', roas: 'ROAS', unavailableProduct: 'Unavailable product', remaining: 'remaining', events: 'events', noCampaignsMatch: 'No campaigns match these filters.', campaignsCount: '{{count}} campaigns', campaignDetails: 'Campaign details, analytics & actions', starts: 'Starts', ends: 'Ends', discount: 'Discount', orderUsage: 'Order usage', auditHistory: 'Audit history', noDescription: 'No description', cta: 'CTA', priority: 'priority', auditAction: 'Audit action', noReasonSupplied: 'No reason supplied.', campaignSchedule: 'Campaign schedule', reasonReviewActions: 'Reason for review actions', reasonPlaceholder: 'Required for rejection or termination. Approval, pause, resume, and delete are immediately available.', completed: 'completed', giveRejectionReason: 'Give the seller a rejection reason:', actionCompleted: '{{action}} completed.',
  orderNo: 'Order No', customer: 'Customer', total: 'Total', payment: 'Payment', date: 'Date', viewDetail: 'View detail', searchOrders: 'Search order no, customer…', orderDescription: 'Inspect checkout state and per-store fulfillment on the detail page', failedLoadOrders: 'Could not load orders. Check your connection and try again.', failedLoad: 'Failed to load', orderDetails: 'Order {{number}}', loadingOrder: 'Loading order…', orderNotFound: 'Order not found', paymentExplanation: 'Payment status follows verified payments and refunds.', viewBuyerWallet: 'View buyer wallet transactions', productSelections: 'Product selections and prescription', adminAction: 'Admin action', refundExplanation: 'Refunds reverse the payment and seller ledger.', deliverySummary: 'Delivery summary',
  sellerConversations: 'Seller conversations', messageSeller: 'Message a seller…', startConversation: 'Start Conversation', start: 'Start', noConversations: 'No conversations yet.', selectConversation: 'Select a seller conversation', typeMessage: 'Type a message…', send: 'Send', sending: 'Sending…', noMessagesYet: 'No messages yet', downloadFile: 'Download file', couldNotLoadConversations: 'Could not load conversations.', couldNotLoadMessages: 'Could not load messages.', failedSendMessage: 'Failed to send message.', couldNotStartConversation: 'Could not start conversation with that seller.',
  status_pending: 'Pending', status_approved: 'Approved', status_rejected: 'Rejected', status_processing: 'Processing', status_completed: 'Completed', status_failed: 'Failed', status_active: 'Active', status_inactive: 'Inactive', status_paused: 'Paused', status_scheduled: 'Scheduled', status_expired: 'Expired', status_cancelled: 'Cancelled', status_draft: 'Draft', status_exhausted: 'Exhausted', status_terminated: 'Terminated', status_invalid: 'Invalid', status_pending_payment: 'Pending payment', status_payment_failed: 'Payment failed', status_pending_review: 'Pending review', status_legacy_review: 'Legacy review', status_reconciliation_hold: 'Reconciliation hold', status_unpaid: 'Unpaid', status_reserved: 'Reserved', status_released: 'Released', status_unverified: 'Unverified', status_in_stock: 'In stock', status_low_stock: 'Low stock', status_out_of_stock: 'Out of stock', status_paid: 'Paid', status_refunded: 'Refunded', status_qualified: 'Qualified', status_rewarded: 'Rewarded', status_suspended: 'Suspended', status_reversed: 'Reversed', status_delivered: 'Delivered', status_shipped: 'Shipped',
};

const it: Record<string, string> = {
  ...en,
  dashboard: 'Dashboard', users: 'Utenti', sellers: 'Venditori', products: 'Prodotti', warehouse: 'Magazzino', boostCampaigns: 'Campagne pubblicitarie', orders: 'Ordini', categories: 'Categorie', coupons: 'Coupon', analytics: 'Analisi', settings: 'Impostazioni', activityLogs: 'Registro attività', points: 'Punti', messages: 'Messaggi', storeReports: 'Segnalazioni negozi', storeBanners: 'Banner negozi', adminPanel: 'Pannello amministrativo', opticalMarketplace: 'Marketplace ottico', logout: 'Esci', admin: 'Amministratore', language: 'Lingua', close: 'Chiudi', cancel: 'Annulla', save: 'Salva', retry: 'Riprova', search: 'Cerca', view: 'Visualizza', details: 'Dettagli', actions: 'Azioni', edit: 'Modifica', delete: 'Elimina', approve: 'Approva', reject: 'Rifiuta', block: 'Blocca', unblock: 'Sblocca', active: 'Attivo', inactive: 'Inattivo', pending: 'In attesa', blocked: 'Bloccato', noResults: 'Nessun risultato trovato.', loading: 'Caricamento…', previous: 'Precedente', next: 'Successivo', pageOf: 'Pagina {{page}} di {{last}}', loginTitle: 'Pannello amministrativo', loginSubtitle: 'Accedi al tuo account', email: 'Email', password: 'Password', loginFailed: 'Accesso non riuscito. Controlla le credenziali.', signingIn: 'Accesso in corso…', signIn: 'Accedi', dashboardWelcome: 'Benvenuto nel pannello amministrativo', dashboardLoadFailed: 'Impossibile caricare le statistiche. Controlla la connessione e la configurazione API.', totalUsers: 'Utenti totali', totalSellers: 'Venditori totali', totalProducts: 'Prodotti totali', totalRevenue: 'Ricavi totali', recentOrders: 'Ordini recenti', noRecentOrders: 'Nessun ordine recente',
  referralProgram: 'Programma referral', referralDescription: 'Monitora acquisizione, finanziamento delle campagne, crediti del portafoglio acquirenti, movimenti del portafoglio venditori e costi della piattaforma.', exportFinancialReport: 'Esporta report finanziario', referralOverview: 'Panoramica', referralCampaigns: 'Campagne', referralRewards: 'Premi', referralAudit: 'Audit', referralAuditLog: 'Registro audit referral', noReferralAudit: 'Nessun registro audit referral.', noReason: 'Nessun motivo registrato', platformReferralSettings: 'Impostazioni referral della piattaforma', referralSettingsDescription: 'Queste impostazioni regolano i premi finanziati dalla piattaforma. Le campagne dei venditori mantengono budget e ambiti propri.', enablePlatformReferral: 'Abilita il programma referral della piattaforma', requireSellerApproval: 'Richiedi approvazione amministrativa per le campagne dei venditori', allowExistingBuyers: 'Consenti acquirenti esistenti nelle campagne dei venditori', allowStacking: 'Consenti cumulo venditore + piattaforma', requireEmail: 'Richiedi email verificata prima del premio', requirePhone: 'Richiedi telefono verificato prima del premio', rewardType: 'Tipo di premio della piattaforma', fixedEur: 'EUR fisso', percentage: 'Percentuale', rewardAmount: 'Importo del premio della piattaforma', maxReward: 'Premio massimo della piattaforma per ordine', minOrder: 'Subtotale minimo qualificante', attributionDays: 'Giorni di attribuzione', waitingDays: 'Giorni di protezione consegna / reso', monthlyLimit: 'Limite mensile dei premi', buyerLimit: 'Limite per acquirente', saveReferralSettings: 'Salva impostazioni referral', saving: 'Salvataggio…', all: 'Tutti', filterStatus: 'Filtra stato', noCampaigns: 'Nessuna campagna referral dei venditori.', noRewards: 'Nessun premio referral per questo filtro.', sellerReferralCampaign: 'Campagna referral del venditore', reward: 'Premio', source: 'Origine', order: 'Ordine', eligibleSubtotal: 'Subtotale qualificante', trace: 'Traccia', buyerTransaction: 'Transazione acquirente', sellerLedger: 'Registro venditore', platformLedger: 'Registro piattaforma', reversal: 'Storno', manualApprove: 'Approva manualmente', suspend: 'Sospendi', reverse: 'Storna', paid: 'pagato', reserved: 'riservato', clicks: 'clic', campaignStatus: 'Stato campagna', approvalStatus: 'Stato approvazione', reasonForAction: 'Motivo dell’azione',
  marketplaceFinance: 'Finanza del marketplace', financeDescription: 'Pagamenti degli acquirenti, saldi dei venditori, storni e pagamenti bancari. Aggiornamento ogni 5 secondi.', sellerBalances: 'Saldi venditori', sellerLedgerFinance: 'Registro venditore', boostAdsRevenue: 'Ricavi Boost Ads', withdrawals: 'Prelievi', buyerWalletTransactions: 'Transazioni portafoglio acquirenti', buyerIdFilter: 'Filtro ID acquirente', noFinancialRecords: 'Nessun record in questa pagina.', unableLoadFinance: 'Impossibile caricare i record finanziari.', available: 'Disponibile', reservedForAds: 'Riservato per annunci', adSpend: 'Spesa annunci', walletTopUps: 'Ricariche portafoglio', pendingEarnings: 'Guadagni in sospeso', reservedWithdrawal: 'Prelievo riservato', disputed: 'Contestato', refundDebt: 'Debito rimborsi', totalEarningsAfterReversals: 'Guadagni totali dopo gli storni', method: 'Metodo', legacy: 'legacy', shipment: 'Spedizione', withdrawal: 'Prelievo', boostCampaign: 'Campagna Boost', ledgerChanges: 'Variazioni registro e saldi risultanti', payoutReference: 'Riferimento pagamento', notRecorded: 'Non registrato', bankTransferHelp: 'Esegui il bonifico tramite il sistema di pagamento. Registra il completamento solo dopo l’esito positivo.', withdrawalAction: 'Azione prelievo', selectAction: 'Seleziona azione', withdrawalNotes: 'Note revisione / pagamento', bankPayoutReference: 'Riferimento pagamento bancario completato', applyWithdrawal: 'Applica azione al prelievo', unableUpdateWithdrawal: 'Impossibile aggiornare il prelievo.',
  userDetails: 'Dettagli utente', userNotFound: 'Utente non trovato', profile: 'Profilo', phone: 'Telefono', created: 'Creato', emailVerified: 'Email verificata', blockAccount: 'Blocca account', unblockAccount: 'Sblocca account', cannotBlockSelf: 'Non puoi modificare lo stato di blocco del tuo account.', failedUpdateUser: 'Impossibile aggiornare l’utente', userBlocked: 'Utente bloccato', userUnblocked: 'Utente sbloccato', manageUsers: 'Crea, blocca e rimuovi acquirenti, venditori e amministratori', createUser: 'Crea utente', editUser: 'Modifica utente', update: 'Aggiorna', searchUsers: 'Cerca utenti…', allRoles: 'Tutti i ruoli', buyer: 'Acquirente', seller: 'Venditore', allAccess: 'Tutti gli accessi', notBlocked: 'Non bloccato', name: 'Nome', role: 'Ruolo', access: 'Accesso', newPassword: 'Nuova password (lascia vuoto per mantenere quella attuale)', userCreated: 'Utente creato correttamente', userUpdated: 'Utente aggiornato correttamente', userDeleted: 'Utente eliminato correttamente', failedLoadUsers: 'Impossibile caricare gli utenti. Controlla la connessione e riprova.', failedSaveUser: 'Impossibile salvare l’utente', failedDeleteUser: 'Impossibile eliminare l’utente', cannotDeleteSelf: 'Non puoi eliminare il tuo account da qui.',
  manageSellers: 'Gestisci venditori e negozi', searchSellers: 'Cerca venditori…', storeName: 'Nome negozio', owner: 'Proprietario', storeDetails: 'Dettagli negozio', sellerNotFound: 'Venditore non trovato', storeApproved: 'Negozio approvato correttamente', storeRejected: 'Negozio rifiutato correttamente', failedLoadSellers: 'Impossibile caricare i venditori', failedApproveStore: 'Impossibile approvare il negozio', failedRejectStore: 'Impossibile rifiutare il negozio', rejectionReason: 'Motivo del rifiuto:', manageProducts: 'Gestisci tutti i prodotti', searchProducts: 'Cerca prodotti…', product: 'Prodotto', sku: 'SKU', store: 'Negozio', category: 'Categoria', price: 'Prezzo', status: 'Stato', approved: 'Approvato', productDetails: 'Dettagli prodotto', productNotFound: 'Prodotto non trovato', productApproved: 'Prodotto approvato correttamente', productRejected: 'Prodotto rifiutato correttamente', productDeleted: 'Prodotto eliminato correttamente', failedLoadProducts: 'Impossibile caricare i prodotti', failedApproveProduct: 'Impossibile approvare il prodotto', failedRejectProduct: 'Impossibile rifiutare il prodotto', failedDeleteProduct: 'Impossibile eliminare il prodotto', confirmDeleteProduct: 'Vuoi davvero eliminare questo prodotto?', viewProduct: 'Visualizza',
  warehouseTitle: 'Magazzino', warehouseDescription: 'Gestisci scorte all’ingrosso, ordini dei venditori, categorie e disponibilità.', addStockProduct: 'Aggiungi prodotto a magazzino', productListings: 'Elenco prodotti', warehouseOrders: 'Ordini magazzino', warehouseCategories: 'Categorie', loadingInventory: 'Caricamento inventario magazzino…', noWarehouseProducts: 'Nessun prodotto di magazzino corrisponde ai filtri.', warehouseStockProduct: 'Prodotto di magazzino', availability: 'Disponibilità', inStock: 'Disponibile', lowStock: 'Scorta bassa', outOfStock: 'Esaurito', addWarehouseProduct: 'Aggiungi prodotto di magazzino', editWarehouseProduct: 'Modifica prodotto di magazzino', wholesaleOnly: 'Solo scorte all’ingrosso. I campi per prescrizioni non sono disponibili.', selectCategory: 'Seleziona categoria', productImage: 'Immagine prodotto', productName: 'Nome prodotto', unitPrice: 'Prezzo unitario (€)', shippingFee: 'Costo spedizione (€)', availableQuantity: 'Quantità disponibile', lowStockAlert: 'Avviso scorta bassa a', color: 'Colore', templeSize: 'Misura asta', lensSize: 'Misura lente', bridgeSize: 'Misura ponte', brand: 'Marca', lensMaterial: 'Materiale lente', replacementFrequency: 'Frequenza sostituzione', packSize: 'Formato confezione', baseCurve: 'Curva base', diameter: 'Diametro', waterContent: 'Contenuto d’acqua', solutionType: 'Tipo soluzione', volume: 'Volume / ml', packType: 'Tipo confezione', expiryDate: 'Data di scadenza', description: 'Descrizione', availableToSellers: 'Disponibile ai venditori', saveProduct: 'Salva prodotto', saveCategory: 'Salva categoria', editWarehouseCategory: 'Modifica categoria magazzino', addWarehouseCategory: 'Aggiungi categoria magazzino', productType: 'Tipo prodotto', archive: 'Archivia', warehouseProductSaved: 'Prodotto di magazzino {{action}} correttamente.', archiveWarehouseProduct: 'Archiviare questo prodotto di magazzino?', warehouseProductArchived: 'Prodotto di magazzino archiviato.', warehouseCategoryArchived: 'Categoria di magazzino archiviata.', warehouseOrderUpdated: 'Ordine di magazzino aggiornato.', warehouseOrder: 'Ordine di magazzino', subtotal: 'Subtotale', shipping: 'Spedizione', paidFromSellerWallet: 'Pagato dal portafoglio venditore', units: 'unità', orderStatus: 'Stato ordine', shippingCarrier: 'Corriere', trackingNumber: 'Numero di tracciamento', shippingNotes: 'Note di spedizione', saveOrder: 'Salva ordine', cancellingPaidOrder: 'L’annullamento di un ordine di magazzino pagato rimborsa il totale nel portafoglio del venditore. Questa operazione non può essere annullata.',
  boostTitle: 'Campagne Boost', boostDescription: 'Revisiona pubblicità dei prodotti, fondi riservati, prestazioni e cronologia audit.', administration: 'Amministrazione', campaignControl: 'Gestione campagne sconto', bannerReview: 'Revisione banner promozionale', campaignReviewDescription: 'Revisiona campagne programmate, cronologia e prestazioni, quindi esegui azioni controllate sul ciclo di vita.', searchCampaigns: 'Cerca campagne', allStatuses: 'Tutti gli stati', allPayments: 'Tutti i pagamenti', allApprovals: 'Tutte le approvazioni', allPlacements: 'Tutti i posizionamenti', sellerId: 'ID venditore', productId: 'ID prodotto', startsFrom: 'Inizia da', startsThrough: 'Inizia fino a', applyFilters: 'Applica filtri', campaignProduct: 'Campagna / prodotto', statusPayment: 'Stato / pagamento', dates: 'Date', budgetRemaining: 'Budget / residuo', spend: 'Spesa', impressions: 'Impressioni', clicksCtr: 'Clic / CTR', cpc: 'CPC', conversionsRevenue: 'Conversioni / ricavi', roas: 'ROAS', unavailableProduct: 'Prodotto non disponibile', remaining: 'residuo', events: 'eventi', noCampaignsMatch: 'Nessuna campagna corrisponde ai filtri.', campaignsCount: '{{count}} campagne', campaignDetails: 'Dettagli, analisi e azioni della campagna', starts: 'Inizio', ends: 'Fine', discount: 'Sconto', orderUsage: 'Utilizzo ordini', auditHistory: 'Cronologia audit', noDescription: 'Nessuna descrizione', cta: 'CTA', priority: 'priorità', auditAction: 'Azione audit', noReasonSupplied: 'Nessun motivo fornito.', campaignSchedule: 'Programmazione campagna', reasonReviewActions: 'Motivo delle azioni di revisione', reasonPlaceholder: 'Obbligatorio per rifiuto o terminazione. Approvazione, pausa, ripresa ed eliminazione sono disponibili subito.', completed: 'completata', giveRejectionReason: 'Indica il motivo del rifiuto al venditore:', actionCompleted: '{{action}} completata.',
  orderNo: 'Numero ordine', customer: 'Cliente', total: 'Totale', payment: 'Pagamento', date: 'Data', viewDetail: 'Visualizza dettaglio', searchOrders: 'Cerca numero ordine, cliente…', orderDescription: 'Controlla lo stato del checkout e l’evasione per negozio nella pagina dei dettagli', failedLoadOrders: 'Impossibile caricare gli ordini. Controlla la connessione e riprova.', failedLoad: 'Caricamento non riuscito', orderDetails: 'Ordine {{number}}', loadingOrder: 'Caricamento ordine…', orderNotFound: 'Ordine non trovato', paymentExplanation: 'Lo stato del pagamento segue pagamenti verificati e rimborsi.', viewBuyerWallet: 'Visualizza transazioni portafoglio acquirente', productSelections: 'Selezioni prodotto e prescrizione', adminAction: 'Azione amministrativa', refundExplanation: 'I rimborsi stornano il pagamento e il registro del venditore.', deliverySummary: 'Riepilogo consegna',
  sellerConversations: 'Conversazioni venditori', messageSeller: 'Scrivi a un venditore…', startConversation: 'Avvia conversazione', start: 'Avvia', noConversations: 'Nessuna conversazione.', selectConversation: 'Seleziona una conversazione con un venditore', typeMessage: 'Scrivi un messaggio…', send: 'Invia', sending: 'Invio…', noMessagesYet: 'Nessun messaggio', downloadFile: 'Scarica file', couldNotLoadConversations: 'Impossibile caricare le conversazioni.', couldNotLoadMessages: 'Impossibile caricare i messaggi.', failedSendMessage: 'Impossibile inviare il messaggio.', couldNotStartConversation: 'Impossibile avviare la conversazione con questo venditore.',
};

Object.assign(en, {
  failed: 'Failed', status_submitted: 'Submitted', status_under_review: 'Under review', status_waiting_for_customer_response: 'Waiting for customer response', status_waiting_for_seller_response: 'Waiting for seller response',
  confirmDeleteUser: 'Are you sure you want to delete this user?', updated: 'updated', created: 'created',
  unableLoadReferrals: 'Unable to load referral administration.', couldNotSaveReferral: 'Could not save referral settings.', couldNotExportReferral: 'Could not export the referral financial report.', actionFailed: 'Action failed.', commission: 'commission', platform: 'Platform',
  requestFailed: 'The request could not be completed.', visibilityUpdated: 'Visibility updated', failedToggleProduct: 'Failed to update product visibility', toggleVisible: 'Toggle visibility', viewAdCampaigns: 'View ad campaigns', productAdvertising: 'Product advertising', campaignStatusPayments: 'Campaign status and payments', rejectProduct: 'Reject product', rejectProductDescription: 'The product will be hidden and marked not approved. Sellers may see this reason.', rejectReasonDescription: 'Please provide a clear reason. The seller or system may show this text where appropriate.', reasonPlaceholderShort: 'Reason…', enterReason: 'Enter at least 3 characters.', submitting: 'Submitting…', confirmReject: 'Confirm reject',
  allAvailability: 'All availability', searchWarehouseProducts: 'Search stock by product or SKU…', searchOrders: 'Search orders…', totalStock: 'Total Stock', items: 'Items', seller: 'Seller', stock: 'Stock', manage: 'Manage', addCategory: 'Add Category', loadingOrders: 'Loading warehouse orders…', noWarehouseOrders: 'No warehouse orders yet.', categoryDeleteWarning: 'Categories with products cannot be deleted.', forSeller: 'for', eyeglasses: 'Eyeglasses', contactLenses: 'Contact Lenses', contactLensSolutions: 'Contact Lens Solutions',
  deliveryAddress: 'Delivery address', legacyOrderWarning: 'Legacy order: financial reconciliation is required before payment or fulfillment.', addressUnavailable: 'Address snapshot unavailable for this legacy order.', escrow: 'Escrow', notFunded: 'not funded', pendingSellerReview: 'Pending seller review. Delivery has not been quoted yet.', estimated: 'Estimated', allocatedDiscount: 'Allocated discount', deliveryVerification: 'Delivery verification', confirmed: 'Confirmed', notConfirmed: 'Not confirmed', deliveryFeeAdded: 'The seller has added the delivery fee. Review the final total before paying.', unableRefreshOrder: 'Unable to refresh order.', orderFinancialHistory: 'Refunded and cancelled shipments retain their original financial records below. Updates every 5 seconds.', sellerDeliveryFees: 'Seller delivery fees', discounts: 'Discounts', buyerDebit: 'Buyer debit', refund: 'Refund', deliveryCodeExplanation: 'Delivery confirmation requires the buyer’s code.', actionReason: 'Action reason', buyerDeliveryCode: 'Buyer delivery code', applying: 'Applying…', applyAction: 'Apply action', resolve_dispute: 'Resolve dispute',
  attachment: 'Attachment', noEvents: 'No events yet', allCampaigns: 'All campaigns', campaign: 'Campaign', confirmAction: 'Confirm {{action}}', reserve: 'Reserve', fromWallet: 'from your wallet', stopDelivery: 'This stops delivery and returns the unused reserved balance', spendingStops: 'New delivery and spending stop immediately.', campaignValidation: 'The campaign must satisfy payment, product, dates and budget checks.', reasonRecorded: 'Reason (recorded in audit history)', processing: 'Processing…', back: 'Back', legacyCampaignWarning: 'Historic payment and remaining funds are unverified. Reconcile it against payment evidence before replacing it.', reconciliationWarning: 'Delivery and financial actions are held because the ledger does not reconcile. An operator must investigate the audit history and ledger.', campaignDates: 'Campaign dates', dailyBudgetUtc: 'Daily budgets reset at 00:00 UTC', targetingPlacements: 'Targeting & placements', unverified: 'Unverified', campaignBudget: 'Campaign budget', remainingReservation: 'Remaining reservation', returnedWallet: 'Returned to wallet', budgetType: 'Budget type', cpcBid: 'CPC bid', uniqueImpressions: 'Unique impressions / day', averageCpc: 'Average CPC', productViews: 'Product views', addToCarts: 'Add to carts', conversionRate: 'Conversion rate', attributedRevenue: 'Attributed revenue', day: 'day', type: 'Type', amount: 'Amount', reservedBalanceAfter: 'Reserved balance after', sourceBalances: 'Source balances', analyticsExplanation: 'Last-click attribution within {{days}} days of payment. Revenue uses order line totals, excluding shipping. Cancelled and refunded store orders reverse conversions.', dailyPerformance: 'Daily performance', byPlacement: 'By placement', byLocation: 'By location', new: 'new', user: 'User', system: 'System', duplicateCampaign: 'Duplicate campaign',
  action_approve: 'Approve', action_reject: 'Reject', action_pause: 'Pause', action_resume: 'Resume', action_terminate: 'Terminate', action_refund: 'Refund', action_pay: 'Pay', action_cancel: 'Cancel', action_delete: 'Delete', action_completed: 'completed',
  financeType_payment: 'Payment', financeType_refund: 'Refund', financeType_top_up: 'Wallet top-up', financeType_withdrawal: 'Withdrawal', financeType_ad_spend: 'Ad spend', financeType_commission: 'Commission', financeType_reversal: 'Reversal', financeType_payout: 'Payout',
  warehouseType_eyeglasses: 'Eyeglasses', warehouseType_contact_lenses: 'Contact lenses', warehouseType_contact_lens_solutions: 'Contact lens solutions',
  status_resolve_dispute: 'Resolve dispute', status_out_for_delivery: 'Out for delivery', status_awaiting_payment: 'Awaiting payment',
  couponLoadFailed: 'Failed to load coupons', couponReenabled: 'Coupon re-enabled', couponDisabled: 'Coupon disabled globally', couponUpdateFailed: 'Failed to update coupon', couponArchiveConfirm: 'Archive this coupon? Existing paid-order history will remain intact.', couponArchived: 'Coupon archived', couponArchiveFailed: 'Failed to archive coupon', couponDetailsFailed: 'Unable to load coupon details', couponOff: 'OFF', couponFreeShipping: 'Free shipping', couponCode: 'Code', couponStore: 'Store', couponDiscount: 'Discount', couponUsages: 'Usages', couponStatus: 'Status', couponActions: 'Actions', couponUnavailable: 'N/A', couponDisabledStatus: 'Disabled', couponActive: 'Active', couponInactive: 'Inactive', couponEnable: 'Re-enable', couponDisable: 'Disable', couponView: 'View', couponArchive: 'Archive', couponSubtitle: 'View and control seller coupons', couponSearch: 'Search coupons...', couponSearchButton: 'Search', couponAllTypes: 'All types', couponPercentage: 'Percentage', couponFixedAmount: 'Fixed amount', couponAllScopes: 'All scopes', couponProducts: 'Products', couponCategories: 'Categories', couponVariants: 'Variants', couponAllStatuses: 'All statuses', couponPaused: 'Paused', couponScheduled: 'Scheduled', couponExpired: 'Expired', couponExhausted: 'Exhausted', couponClose: 'Close', couponType: 'Type', couponScope: 'Scope', couponUsage: 'Usage', couponUsageHistory: 'Usage history', couponAuditHistory: 'Audit history', couponNoUsage: 'No usage yet.', couponNoAudits: 'No audit events yet.', couponReservation: 'Reservation',
});
Object.assign(it, {
  failed: 'Fallito', status_submitted: 'Inviata', status_under_review: 'In revisione', status_waiting_for_customer_response: 'In attesa della risposta dell’acquirente', status_waiting_for_seller_response: 'In attesa della risposta del venditore',
  confirmDeleteUser: 'Vuoi davvero eliminare questo utente?', updated: 'aggiornato', created: 'creato', unableLoadReferrals: 'Impossibile caricare la gestione referral.', couldNotSaveReferral: 'Impossibile salvare le impostazioni referral.', couldNotExportReferral: 'Impossibile esportare il report finanziario referral.', actionFailed: 'Azione non riuscita.', commission: 'commissione', platform: 'Piattaforma', requestFailed: 'La richiesta non può essere completata.', visibilityUpdated: 'Visibilità aggiornata', failedToggleProduct: 'Impossibile aggiornare la visibilità del prodotto', toggleVisible: 'Modifica visibilità', viewAdCampaigns: 'Visualizza campagne pubblicitarie', productAdvertising: 'Pubblicità del prodotto', campaignStatusPayments: 'Stato e pagamenti della campagna', rejectProduct: 'Rifiuta prodotto', rejectProductDescription: 'Il prodotto sarà nascosto e segnato come non approvato. I venditori potrebbero vedere questo motivo.', rejectReasonDescription: 'Inserisci un motivo chiaro. Il venditore o il sistema potrebbe mostrare questo testo.', reasonPlaceholderShort: 'Motivo…', enterReason: 'Inserisci almeno 3 caratteri.', submitting: 'Invio…', confirmReject: 'Conferma rifiuto', allAvailability: 'Tutte le disponibilità', searchWarehouseProducts: 'Cerca scorte per prodotto o SKU…', searchOrders: 'Cerca ordini…', totalStock: 'Scorta totale', items: 'Articoli', stock: 'Scorta', manage: 'Gestisci', addCategory: 'Aggiungi categoria', loadingOrders: 'Caricamento ordini magazzino…', noWarehouseOrders: 'Nessun ordine di magazzino.', categoryDeleteWarning: 'Le categorie con prodotti non possono essere eliminate.', forSeller: 'per', eyeglasses: 'Occhiali', contactLenses: 'Lenti a contatto', contactLensSolutions: 'Soluzioni per lenti a contatto', deliveryAddress: 'Indirizzo di consegna', legacyOrderWarning: 'Ordine legacy: è necessaria una riconciliazione finanziaria prima del pagamento o dell’evasione.', addressUnavailable: 'Indirizzo non disponibile per questo ordine legacy.', escrow: 'Deposito', notFunded: 'non finanziato', pendingSellerReview: 'In attesa della revisione del venditore. La consegna non è ancora stata quotata.', estimated: 'Stimata', allocatedDiscount: 'Sconto allocato', deliveryVerification: 'Verifica consegna', confirmed: 'Confermata', notConfirmed: 'Non confermata', deliveryFeeAdded: 'Il venditore ha aggiunto il costo di consegna. Controlla il totale finale prima di pagare.', unableRefreshOrder: 'Impossibile aggiornare l’ordine.', orderFinancialHistory: 'Le spedizioni rimborsate e annullate conservano sotto i record finanziari originali. Aggiornamento ogni 5 secondi.', sellerDeliveryFees: 'Costi consegna venditore', discounts: 'Sconti', buyerDebit: 'Addebito acquirente', refund: 'Rimborso', deliveryCodeExplanation: 'La conferma della consegna richiede il codice dell’acquirente.', actionReason: 'Motivo dell’azione', buyerDeliveryCode: 'Codice consegna acquirente', applying: 'Applicazione…', applyAction: 'Applica azione',
  attachment: 'Allegato', noEvents: 'Nessun evento', allCampaigns: 'Tutte le campagne', campaign: 'Campagna', confirmAction: 'Conferma {{action}}', reserve: 'Riserva', fromWallet: 'dal tuo portafoglio', stopDelivery: 'Questa azione interrompe la consegna e restituisce il saldo riservato inutilizzato', spendingStops: 'La nuova consegna e la spesa si fermano immediatamente.', campaignValidation: 'La campagna deve rispettare i controlli su pagamento, prodotto, date e budget.', reasonRecorded: 'Motivo (registrato nella cronologia audit)', processing: 'Elaborazione…', back: 'Indietro', legacyCampaignWarning: 'Il pagamento storico e i fondi residui non sono verificati. Riconciliali con le prove di pagamento prima di sostituire la campagna.', reconciliationWarning: 'Le azioni di consegna e finanziarie sono sospese perché il registro non è riconciliato.', campaignDates: 'Date campagna', dailyBudgetUtc: 'I budget giornalieri si azzerano alle 00:00 UTC', targetingPlacements: 'Target e posizionamenti', unverified: 'Non verificato', campaignBudget: 'Budget campagna', remainingReservation: 'Riserva residua', returnedWallet: 'Restituito al portafoglio', budgetType: 'Tipo budget', cpcBid: 'Offerta CPC', uniqueImpressions: 'Impressioni uniche / giorno', averageCpc: 'CPC medio', productViews: 'Visualizzazioni prodotto', addToCarts: 'Aggiunte al carrello', conversionRate: 'Tasso di conversione', attributedRevenue: 'Ricavi attribuiti', day: 'giorno', type: 'Tipo', amount: 'Importo', reservedBalanceAfter: 'Saldo riservato dopo', sourceBalances: 'Saldi origine', analyticsExplanation: 'Attribuzione dell’ultimo clic entro {{days}} giorni dal pagamento. I ricavi usano i totali delle righe ordine, escluse le spedizioni.', dailyPerformance: 'Prestazioni giornaliere', byPlacement: 'Per posizionamento', byLocation: 'Per località', new: 'nuovo', user: 'Utente', system: 'Sistema', duplicateCampaign: 'Duplica campagna', action_approve: 'Approva', action_reject: 'Rifiuta', action_pause: 'Pausa', action_resume: 'Riprendi', action_terminate: 'Termina', action_refund: 'Rimborsa', action_pay: 'Paga', action_cancel: 'Annulla', action_delete: 'Elimina', action_completed: 'completata', financeType_payment: 'Pagamento', financeType_refund: 'Rimborso', financeType_top_up: 'Ricarica portafoglio', financeType_withdrawal: 'Prelievo', financeType_ad_spend: 'Spesa annunci', financeType_commission: 'Commissione', financeType_reversal: 'Storno', financeType_payout: 'Pagamento', warehouseType_eyeglasses: 'Occhiali', warehouseType_contact_lenses: 'Lenti a contatto', warehouseType_contact_lens_solutions: 'Soluzioni per lenti a contatto', status_resolve_dispute: 'Risolvi contestazione', status_out_for_delivery: 'In consegna', status_awaiting_payment: 'In attesa del pagamento',
  couponLoadFailed: 'Impossibile caricare i coupon', couponReenabled: 'Coupon riattivato', couponDisabled: 'Coupon disabilitato globalmente', couponUpdateFailed: 'Impossibile aggiornare il coupon', couponArchiveConfirm: 'Archiviare questo coupon? La cronologia degli ordini pagati rimarrà invariata.', couponArchived: 'Coupon archiviato', couponArchiveFailed: 'Impossibile archiviare il coupon', couponDetailsFailed: 'Impossibile caricare i dettagli del coupon', couponOff: 'SCONTO', couponFreeShipping: 'Spedizione gratuita', couponCode: 'Codice', couponStore: 'Negozio', couponDiscount: 'Sconto', couponUsages: 'Utilizzi', couponStatus: 'Stato', couponActions: 'Azioni', couponUnavailable: 'N/D', couponDisabledStatus: 'Disabilitato', couponActive: 'Attivo', couponInactive: 'Inattivo', couponEnable: 'Riattiva', couponDisable: 'Disabilita', couponView: 'Visualizza', couponArchive: 'Archivia', couponSubtitle: 'Visualizza e controlla i coupon dei venditori', couponSearch: 'Cerca coupon...', couponSearchButton: 'Cerca', couponAllTypes: 'Tutti i tipi', couponPercentage: 'Percentuale', couponFixedAmount: 'Importo fisso', couponAllScopes: 'Tutti gli ambiti', couponProducts: 'Prodotti', couponCategories: 'Categorie', couponVariants: 'Varianti', couponAllStatuses: 'Tutti gli stati', couponPaused: 'In pausa', couponScheduled: 'Programmato', couponExpired: 'Scaduto', couponExhausted: 'Esaurito', couponClose: 'Chiudi', couponType: 'Tipo', couponScope: 'Ambito', couponUsage: 'Utilizzo', couponUsageHistory: 'Cronologia utilizzi', couponAuditHistory: 'Cronologia audit', couponNoUsage: 'Nessun utilizzo.', couponNoAudits: 'Nessun evento di audit.', couponReservation: 'Prenotazione',
});
Object.assign(en, { conversions: 'Conversions', escrowAmount: 'Escrow amount', notApproved: 'Not approved', sellerDeliveryFee: 'Seller delivery fee' });
Object.assign(it, { conversions: 'Conversioni', escrowAmount: 'Importo deposito', notApproved: 'Non approvato', sellerDeliveryFee: 'Costo consegna venditore' });
Object.assign(en, { notAvailable: 'N/A' });
Object.assign(it, { notAvailable: 'N/D' });
Object.assign(en, { paymentMethod_card: 'Card', paymentMethod_bank_transfer: 'Bank transfer', paymentMethod_wallet: 'Wallet', paymentMethod_cash: 'Cash' });
Object.assign(it, { paymentMethod_card: 'Carta', paymentMethod_bank_transfer: 'Bonifico bancario', paymentMethod_wallet: 'Portafoglio', paymentMethod_cash: 'Contanti' });
Object.assign(en, { unreadNotifications: '{{count}} unread notifications', reminder_orders: 'New or pending orders need attention.', reminder_messages: 'New admin messages are waiting.', reminder_support: 'Support tickets need attention.', reminder_sellers: 'Seller approvals are waiting.', reminder_products: 'Products are waiting for review.', reminder_reports: 'Store reports need attention.', reminder_banners: 'Banners are waiting for approval.', reminder_boost_campaigns: 'Boost campaigns are waiting for review.', reminder_referrals: 'Referral campaigns are waiting for approval.', reminder_withdrawals: 'Seller withdrawals are waiting for review.' });
Object.assign(it, { unreadNotifications: '{{count}} notifiche non lette', reminder_orders: 'Ci sono ordini nuovi o in attesa di attenzione.', reminder_messages: 'Ci sono nuovi messaggi amministrativi.', reminder_support: 'I ticket di supporto richiedono attenzione.', reminder_sellers: 'Ci sono approvazioni venditore in attesa.', reminder_products: 'Ci sono prodotti in attesa di revisione.', reminder_reports: 'Ci sono segnalazioni negozio da verificare.', reminder_banners: 'Ci sono banner in attesa di approvazione.', reminder_boost_campaigns: 'Ci sono campagne Boost in attesa di revisione.', reminder_referrals: 'Ci sono campagne referral in attesa di approvazione.', reminder_withdrawals: 'Ci sono prelievi venditore in attesa di revisione.' });
Object.assign(en, { support: 'Support', discountCampaigns: 'Discount Campaigns', 'Marketplace Finance': 'Marketplace Finance', 'Referral Program': 'Referral Program', 'Discount Campaigns': 'Discount Campaigns' });
Object.assign(it, { support: 'Supporto', discountCampaigns: 'Campagne sconto', 'Marketplace Finance': 'Finanza del marketplace', 'Referral Program': 'Programma referral', 'Discount Campaigns': 'Campagne sconto' });
Object.assign(en, { revenue: 'Revenue', transactions: 'Transactions', date: 'Date', items: 'Items', stock: 'Stock', manage: 'Manage', totalStock: 'Total Stock', seller: 'Seller',
  status_resolve_dispute: 'Resolve dispute', status_out_for_delivery: 'Out for delivery', status_awaiting_payment: 'Awaiting payment' });
Object.assign(it, { revenue: 'Ricavi', transactions: 'Transazioni', date: 'Data', items: 'Articoli', stock: 'Scorta', manage: 'Gestisci', totalStock: 'Scorta totale', seller: 'Venditore',
  status_resolve_dispute: 'Risolvi contestazione', status_out_for_delivery: 'In consegna', status_awaiting_payment: 'In attesa del pagamento' });
Object.assign(en, { referralAction_approve: 'Approve', referralAction_reject: 'Reject', referralAction_suspend: 'Suspend', referralAction_reverse: 'Reverse', referralAction_archive: 'Archive', placement_homepage_hero: 'Homepage hero', placement_homepage_featured: 'Homepage featured', placement_category_page: 'Category page', placement_store_page: 'Store page', placement_sidebar: 'Sidebar', deliveryMethod_standard: 'Standard delivery', deliveryMethod_express: 'Express delivery', deliveryMethod_pickup: 'Pickup' });
Object.assign(it, { referralAction_approve: 'Approva', referralAction_reject: 'Rifiuta', referralAction_suspend: 'Sospendi', referralAction_reverse: 'Storna', referralAction_archive: 'Archivia', placement_homepage_hero: 'Hero home page', placement_homepage_featured: 'In evidenza home page', placement_category_page: 'Pagina categoria', placement_store_page: 'Pagina negozio', placement_sidebar: 'Barra laterale', deliveryMethod_standard: 'Consegna standard', deliveryMethod_express: 'Consegna express', deliveryMethod_pickup: 'Ritiro' });
Object.assign(en, { referralSource_platform: 'Platform', referralSource_seller_campaign: 'Seller campaign', referralSource_direct: 'Direct', referralSource_unknown: 'Unknown' });
Object.assign(it, { referralSource_platform: 'Piattaforma', referralSource_seller_campaign: 'Campagna venditore', referralSource_direct: 'Diretto', referralSource_unknown: 'Sconosciuto' });
Object.assign(it, { status_pending: 'In attesa', status_approved: 'Approvato', status_rejected: 'Rifiutato', status_processing: 'In elaborazione', status_completed: 'Completato', status_failed: 'Fallito', status_active: 'Attivo', status_inactive: 'Inattivo', status_paused: 'In pausa', status_scheduled: 'Programmato', status_expired: 'Scaduto', status_cancelled: 'Annullato', status_draft: 'Bozza', status_exhausted: 'Esaurito', status_terminated: 'Terminato', status_invalid: 'Non valido', status_pending_payment: 'Pagamento in attesa', status_payment_failed: 'Pagamento fallito', status_pending_review: 'Revisione in attesa', status_legacy_review: 'Revisione legacy', status_reconciliation_hold: 'Riconciliazione sospesa', status_unpaid: 'Non pagato', status_reserved: 'Riservato', status_released: 'Rilasciato', status_unverified: 'Non verificato', status_in_stock: 'Disponibile', status_low_stock: 'Scorta bassa', status_out_of_stock: 'Esaurito', status_paid: 'Pagato', status_refunded: 'Rimborsato', status_qualified: 'Qualificato', status_rewarded: 'Premiato', status_suspended: 'Sospeso', status_reversed: 'Stornato', status_delivered: 'Consegnato', status_shipped: 'Spedito' });

Object.assign(en, { draftProducts: 'Draft Products', bestSellingProducts: 'Best-Selling Products', warehouseOrdersTrend: 'Warehouse Orders Trend', stockByCategory: 'Stock by Category', lastSixMonths: 'Last 6 months', noSalesData: 'No warehouse sales yet.', saveAsDraft: 'Save as draft', draftProductHint: 'Draft products are hidden from sellers until published.' });
Object.assign(it, { draftProducts: 'Prodotti in bozza', bestSellingProducts: 'Prodotti più venduti', warehouseOrdersTrend: 'Andamento ordini magazzino', stockByCategory: 'Scorte per categoria', lastSixMonths: 'Ultimi 6 mesi', noSalesData: 'Non ci sono ancora vendite di magazzino.', saveAsDraft: 'Salva come bozza', draftProductHint: 'I prodotti in bozza restano nascosti ai venditori finché non vengono pubblicati.' });

Object.assign(en, {
  dashboardPlatformOverview: 'Platform Overview', dashboardPlatformSubtitle: 'Your optical marketplace at a glance', dashboardDateRange: 'Dashboard date range', dashboardLastSixMonths: 'Last 6 months', dashboardLastNineMonths: 'Last 9 months', dashboardLastTwelveMonths: 'Last 12 months', dashboardExportReport: 'Export Report', dashboardMetric: 'Metric', dashboardValue: 'Value', dashboardTotalBuyers: 'Total Buyers', dashboardTotalOrders: 'Total Orders', dashboardOrderRevenue: 'Order Revenue', dashboardAdRevenue: 'Ad Spend', dashboardWarehouseRevenue: 'Warehouse Revenue', dashboardVsPreviousMonth: 'vs. previous month', dashboardRevenuePerformance: 'Revenue Performance', dashboardOrderStatus: 'Order Status', dashboardNoOrderData: 'No order activity yet.', dashboardMonthlyOrdersGmv: 'Monthly Orders & GMV', dashboardOrders: 'Orders', dashboardGmv: 'GMV', dashboardWarehouseOverview: 'Warehouse Overview', dashboardTotalStock: 'Total Stock', dashboardLowStockAlert: 'Low-Stock Alert', dashboardWarehouseTrend: 'Warehouse Trend', dashboardRevenueSources: 'Revenue Sources', dashboardProducts: 'Products', dashboardSellerStore: 'Seller / Store', dashboardUnitsSold: 'Units Sold', dashboardNoSalesData: 'No product sales in this period.', dashboardRecentActivity: 'Recent Activity', dashboardLive: 'Live', dashboardNoActivity: 'No activity yet.', dashboardKeyInsights: 'Key Insights', dashboardRevenueUp: 'Revenue is up', dashboardRevenueDown: 'Revenue is down', dashboardOpenOrders: 'Open orders', dashboardLowStockItems: 'Low-stock items', dashboardOpenSupport: 'Open support tickets', dashboardCountNeedsAttention: '{{count}} need attention.', dashboardActivityOrder: 'Order {{reference}} placed', dashboardActivityWarehouse: 'Warehouse order {{reference}} paid', dashboardActivityCampaign: 'Campaign {{reference}} updated', dashboardActivitySeller: 'Seller store {{reference}} joined', dashboardActivitySupport: 'Support ticket {{reference}} updated',
});
Object.assign(it, {
  dashboardPlatformOverview: 'Panoramica della piattaforma', dashboardPlatformSubtitle: 'Il tuo marketplace ottico in sintesi', dashboardDateRange: 'Intervallo date dashboard', dashboardLastSixMonths: 'Ultimi 6 mesi', dashboardLastNineMonths: 'Ultimi 9 mesi', dashboardLastTwelveMonths: 'Ultimi 12 mesi', dashboardExportReport: 'Esporta report', dashboardMetric: 'Metrica', dashboardValue: 'Valore', dashboardTotalBuyers: 'Acquirenti totali', dashboardTotalOrders: 'Ordini totali', dashboardOrderRevenue: 'Ricavi dagli ordini', dashboardAdRevenue: 'Spesa pubblicitaria', dashboardWarehouseRevenue: 'Ricavi magazzino', dashboardVsPreviousMonth: 'rispetto al mese precedente', dashboardRevenuePerformance: 'Andamento ricavi', dashboardOrderStatus: 'Stato ordini', dashboardNoOrderData: 'Nessuna attività ordine.', dashboardMonthlyOrdersGmv: 'Ordini mensili e GMV', dashboardOrders: 'Ordini', dashboardGmv: 'GMV', dashboardWarehouseOverview: 'Panoramica magazzino', dashboardTotalStock: 'Scorte totali', dashboardLowStockAlert: 'Avviso scorte basse', dashboardWarehouseTrend: 'Andamento magazzino', dashboardRevenueSources: 'Fonti dei ricavi', dashboardProducts: 'Prodotti', dashboardSellerStore: 'Venditore / Negozio', dashboardUnitsSold: 'Unità vendute', dashboardNoSalesData: 'Nessuna vendita prodotto nel periodo.', dashboardRecentActivity: 'Attività recenti', dashboardLive: 'In tempo reale', dashboardNoActivity: 'Nessuna attività.', dashboardKeyInsights: 'Insight principali', dashboardRevenueUp: 'Ricavi in crescita', dashboardRevenueDown: 'Ricavi in calo', dashboardOpenOrders: 'Ordini aperti', dashboardLowStockItems: 'Articoli a scorta bassa', dashboardOpenSupport: 'Ticket supporto aperti', dashboardCountNeedsAttention: '{{count}} richiedono attenzione.', dashboardActivityOrder: 'Ordine {{reference}} effettuato', dashboardActivityWarehouse: 'Ordine magazzino {{reference}} pagato', dashboardActivityCampaign: 'Campagna {{reference}} aggiornata', dashboardActivitySeller: 'Negozio venditore {{reference}} aggiunto', dashboardActivitySupport: 'Ticket supporto {{reference}} aggiornato',
});

Object.assign(en, {
  sidebarUsersSellers: 'Users & Sellers', sidebarProductsOperations: 'Products & Operations', sidebarCampaignsMarketing: 'Campaigns & Marketing', sidebarReportsCommunication: 'Reports & Communication', sidebarFinanceGrowth: 'Finance & Growth', sidebarSystem: 'System',
});
Object.assign(it, {
  sidebarUsersSellers: 'Utenti e venditori', sidebarProductsOperations: 'Prodotti e operazioni', sidebarCampaignsMarketing: 'Campagne e marketing', sidebarReportsCommunication: 'Report e comunicazioni', sidebarFinanceGrowth: 'Finanza e crescita', sidebarSystem: 'Sistema',
});

Object.assign(en, {
  supportTickets: 'Support Tickets', refresh: 'Refresh', selectTicket: 'Select a ticket.', replyToUser: 'Reply to user',
  supportNoTickets: 'No support tickets found.', supportStatus: 'Ticket status', supportUser: 'User',
  status_open: 'Open', status_in_progress: 'In progress', status_waiting_for_user: 'Waiting for user', status_resolved: 'Resolved', status_closed: 'Closed',
  failedLoadStoreReports: 'Failed to load store reports', reportStatusUpdated: 'Report status updated', failedUpdateReport: 'Failed to update report',
  warningReasonPrompt: 'Warning reason (private, not shown on public site):', sellerWarned: 'Seller warned', failedWarnSeller: 'Failed to warn seller',
  confirmSuspendStore: 'Suspend store “{{name}}”?', storeSuspended: 'Store suspended', failedSuspendStore: 'Failed to suspend store',
  confirmBlockStore: 'Block store “{{name}}”? This suspends the store and revokes sessions.', storeBlocked: 'Store blocked', failedBlockStore: 'Failed to block store',
  storeReportPrivateDescription: 'Private fraud/abuse reports from buyers — not shown on the public site', storeSuspendedBadge: 'Store suspended',
  buyerLabel: 'Buyer', evidence: 'Evidence', manage: 'Manage', reportLabel: 'Report #{{id}}', reportPrivateAdmin: 'Status updates and seller actions are private (admin-only).',
  adminNotesPrivate: 'Admin notes (optional, private)', updateStatus: 'Update status', sellerActions: 'Seller actions', warnSeller: 'Warn seller', suspendStore: 'Suspend store', blockStore: 'Block store',
  categoriesDescription: 'Full tree: parent, subcategory, and sub-subcategory. English title and slug are fixed after creation; add Italian titles here.',
  createCategory: 'Create category', searchCategories: 'Search name, Italian title, or slug (all levels)…', filter: 'Filter', couldNotLoadCategories: 'Could not load categories.',
  categoryLoadFailed: 'Failed to load categories', categoryCreated: 'Category created', categoryCreateFailed: 'Create failed', categoryUpdated: 'Category updated', categoryUpdateFailed: 'Update failed',
  noCategories: 'No categories', noCategoriesMatch: 'No categories match this filter', editItalianSettings: 'Edit Italian & settings', topLevel: 'Top level',
  categoryCreateDescription: 'English name and slug are set once at creation. You can add Italian below; tree placement uses parent.',
  categoryEditDescription: 'English name and slug cannot be changed or deleted from admin. Use Italian title for shoppers in Italy.',
  englishNameFixed: 'English name (fixed after save)', englishNameReadOnly: 'English name (read-only)', urlSlug: 'URL slug', slugReadOnly: 'Slug (read-only)', italianTitleOptional: 'Italian title (optional)',
  italianTitle: 'Italian title', parentOptional: 'Parent (optional)', description: 'Description', sortOrder: 'Sort order', topLevelCategory: 'Top level', create: 'Create',
  pointManagement: 'Points Management', pointsDescription: 'Manage point rules and view transactions', pointRules: 'Point Rules', pointTransactions: 'Point Transactions',
  transactions: 'Transactions', createNewRule: 'Create New Rule', editRule: 'Edit Rule', ruleName: 'Name', pointType: 'Type', points: 'Points', redemption: 'Redemption',
  balanceAfter: 'Balance After', pointDescription: 'Description', purchase: 'Purchase', referral: 'Referral', review: 'Review', signup: 'Signup', birthday: 'Birthday', socialShare: 'Social Share',
  pointsPerEuro: 'Points Per Euro', fixedPoints: 'Fixed Points', redemptionRate: 'Redemption Rate (points per €1)', minRedemptionPoints: 'Min Redemption Points', maxRedemptionPerOrder: 'Max Redemption Per Order (€)',
  ruleUpdated: 'Rule updated successfully', ruleCreated: 'Rule created successfully', failedLoadPoints: 'Failed to load data', failedSaveRule: 'Failed to save rule', ruleStatus: 'Status', ruleActions: 'Actions', updateRule: 'Update',
  analyticsDescription: 'Platform analytics and insights', day: 'Day', week: 'Week', month: 'Month', year: 'Year', revenueForPeriod: 'Revenue ({{period}})', paidOrdersRecent: 'Paid orders (recent)', newUsersRecent: 'New users (recent)',
  userGrowth: 'User growth', salesTrends: 'Sales trends (orders / day)', topProductsByViews: 'Top products (by views)', views: 'views', noDataForPeriod: 'No data for this period', noProductData: 'No product data available',
  settingsDescription: 'Platform configuration', loadingSettings: 'Loading settings…', failedLoadSettings: 'Failed to load settings', settingsUpdated: 'Settings updated successfully', failedUpdateSettings: 'Failed to update settings',
  generalSettings: 'General Settings', platformName: 'Platform Name', platformEmail: 'Platform Email', currency: 'Currency', pointsSystem: 'Points System', enablePointsSystem: 'Enable Points System', saveSettings: 'Save Settings',
  activityLogsDescription: 'View all admin activities', failedLoadActivityLogs: 'Failed to load activity logs', resource: 'Resource', success: 'Success',
  campaignSearch: 'Search campaigns', approval: 'Approval', placement: 'Placement', campaign: 'Campaign', scopePlacement: 'Scope / placement', scheduledBrowserTimezone: 'Scheduled in your browser timezone', performance: 'Performance',
  noDescription: 'No description', approvalPrefix: 'Approval: {{value}}', discountOff: '{{value}} {{unit}} off', fixedDiscount: 'fixed', eventCount: 'events', loadingCampaigns: 'Loading campaigns…', noCampaignsFilters: 'No campaigns match these filters.',
  pageLabel: 'Page {{page}} of {{last}}', campaignDetailsAnalyticsActions: 'Campaign details, analytics & actions', promotionalBannerReview: 'Promotional Banner Review', discountCampaignControl: 'Discount Campaign Control',
  campaignReviewDescription: 'Review scheduled campaigns, inspect history and performance, and take controlled lifecycle actions.', datesTimezoneDescription: 'Dates and audit events are shown in your current browser timezone.',
  campaignStatusLabel: 'Status', campaignStarts: 'Starts', campaignEnds: 'Ends', campaignApproval: 'Approval', campaignDiscount: 'Discount', cta: 'CTA', analytics: 'Analytics', orderUsage: 'Order usage',
  auditHistory: 'Audit history', auditAction: 'Audit action', noReasonSupplied: 'No reason supplied.', campaignSchedule: 'Campaign schedule', reasonReviewActions: 'Reason for review actions',
  campaignReasonPlaceholder: 'Required for rejection or termination. Approval, pause, resume, and delete are immediately available.', giveRejectionReason: 'Give the seller a rejection reason:', actionCompleted: '{{action}} completed.',
  metric_orders: 'Orders', metric_impressions: 'Impressions', metric_clicks: 'Clicks', metric_conversions: 'Conversions', metric_revenue: 'Revenue', metric_views: 'Views',
  campaignScope_store: 'Store', campaignScope_product: 'Product', campaignScope_category: 'Category', campaignScope_platform: 'Platform', discountType_percentage: 'percentage', discountType_fixed: 'fixed',
});

Object.assign(it, {
  supportTickets: 'Ticket di supporto', refresh: 'Aggiorna', selectTicket: 'Seleziona un ticket.', replyToUser: 'Rispondi all’utente',
  supportNoTickets: 'Nessun ticket di supporto trovato.', supportStatus: 'Stato del ticket', supportUser: 'Utente',
  status_open: 'Aperto', status_in_progress: 'In corso', status_waiting_for_user: 'In attesa dell’utente', status_resolved: 'Risolto', status_closed: 'Chiuso',
  failedLoadStoreReports: 'Impossibile caricare le segnalazioni dei negozi', reportStatusUpdated: 'Stato segnalazione aggiornato', failedUpdateReport: 'Impossibile aggiornare la segnalazione',
  warningReasonPrompt: 'Motivo dell’avviso (privato, non mostrato sul sito pubblico):', sellerWarned: 'Venditore avvisato', failedWarnSeller: 'Impossibile avvisare il venditore',
  confirmSuspendStore: 'Sospendere il negozio “{{name}}”?', storeSuspended: 'Negozio sospeso', failedSuspendStore: 'Impossibile sospendere il negozio',
  confirmBlockStore: 'Bloccare il negozio “{{name}}”? Questa azione sospende il negozio e revoca le sessioni.', storeBlocked: 'Negozio bloccato', failedBlockStore: 'Impossibile bloccare il negozio',
  storeReportPrivateDescription: 'Segnalazioni private di frode/abuso dagli acquirenti — non visibili sul sito pubblico', storeSuspendedBadge: 'Negozio sospeso',
  buyerLabel: 'Acquirente', evidence: 'Prova', manage: 'Gestisci', reportLabel: 'Segnalazione n. {{id}}', reportPrivateAdmin: 'Gli aggiornamenti e le azioni sul venditore sono privati (solo amministratori).',
  adminNotesPrivate: 'Note amministratore (facoltative, private)', updateStatus: 'Aggiorna stato', sellerActions: 'Azioni venditore', warnSeller: 'Avvisa venditore', suspendStore: 'Sospendi negozio', blockStore: 'Blocca negozio',
  categoriesDescription: 'Albero completo: categoria principale, sottocategoria e livelli successivi. Il titolo inglese e lo slug sono fissi dopo la creazione; aggiungi qui i titoli italiani.',
  createCategory: 'Crea categoria', searchCategories: 'Cerca nome, titolo italiano o slug (tutti i livelli)…', filter: 'Filtra', couldNotLoadCategories: 'Impossibile caricare le categorie.',
  categoryLoadFailed: 'Impossibile caricare le categorie', categoryCreated: 'Categoria creata', categoryCreateFailed: 'Creazione non riuscita', categoryUpdated: 'Categoria aggiornata', categoryUpdateFailed: 'Aggiornamento non riuscito',
  noCategories: 'Nessuna categoria', noCategoriesMatch: 'Nessuna categoria corrisponde al filtro', editItalianSettings: 'Modifica italiano e impostazioni', topLevel: 'Livello principale',
  categoryCreateDescription: 'Il nome inglese e lo slug vengono impostati alla creazione. Puoi aggiungere qui l’italiano; la posizione nell’albero usa la categoria principale.',
  categoryEditDescription: 'Il nome inglese e lo slug non possono essere modificati o eliminati dall’amministrazione. Usa il titolo italiano per gli acquirenti in Italia.',
  englishNameFixed: 'Nome inglese (fisso dopo il salvataggio)', englishNameReadOnly: 'Nome inglese (sola lettura)', urlSlug: 'Slug URL', slugReadOnly: 'Slug (sola lettura)', italianTitleOptional: 'Titolo italiano (facoltativo)',
  italianTitle: 'Titolo italiano', parentOptional: 'Categoria principale (facoltativa)', description: 'Descrizione', sortOrder: 'Ordine', topLevelCategory: 'Livello principale', create: 'Crea',
  pointManagement: 'Gestione punti', pointsDescription: 'Gestisci le regole dei punti e visualizza le transazioni', pointRules: 'Regole punti', pointTransactions: 'Transazioni punti',
  transactions: 'Transazioni', createNewRule: 'Crea nuova regola', editRule: 'Modifica regola', ruleName: 'Nome', pointType: 'Tipo', points: 'Punti', redemption: 'Riscatto',
  balanceAfter: 'Saldo dopo', pointDescription: 'Descrizione', purchase: 'Acquisto', referral: 'Referral', review: 'Recensione', signup: 'Registrazione', birthday: 'Compleanno', socialShare: 'Condivisione social',
  pointsPerEuro: 'Punti per euro', fixedPoints: 'Punti fissi', redemptionRate: 'Tasso di riscatto (punti per €1)', minRedemptionPoints: 'Minimo punti per il riscatto', maxRedemptionPerOrder: 'Massimo riscatto per ordine (€)',
  ruleUpdated: 'Regola aggiornata con successo', ruleCreated: 'Regola creata con successo', failedLoadPoints: 'Impossibile caricare i dati', failedSaveRule: 'Impossibile salvare la regola', ruleStatus: 'Stato', ruleActions: 'Azioni', updateRule: 'Aggiorna',
  analyticsDescription: 'Analisi e informazioni sulla piattaforma', day: 'Giorno', week: 'Settimana', month: 'Mese', year: 'Anno', revenueForPeriod: 'Ricavi ({{period}})', paidOrdersRecent: 'Ordini pagati (recenti)', newUsersRecent: 'Nuovi utenti (recenti)',
  userGrowth: 'Crescita utenti', salesTrends: 'Andamento vendite (ordini / giorno)', topProductsByViews: 'Prodotti più visualizzati', views: 'visualizzazioni', noDataForPeriod: 'Nessun dato per questo periodo', noProductData: 'Nessun dato prodotto disponibile',
  settingsDescription: 'Configurazione della piattaforma', loadingSettings: 'Caricamento impostazioni…', failedLoadSettings: 'Impossibile caricare le impostazioni', settingsUpdated: 'Impostazioni aggiornate con successo', failedUpdateSettings: 'Impossibile aggiornare le impostazioni',
  generalSettings: 'Impostazioni generali', platformName: 'Nome piattaforma', platformEmail: 'Email piattaforma', currency: 'Valuta', pointsSystem: 'Sistema punti', enablePointsSystem: 'Abilita sistema punti', saveSettings: 'Salva impostazioni',
  activityLogsDescription: 'Visualizza tutte le attività amministrative', resource: 'Risorsa', success: 'Riuscito',
  campaignSearch: 'Cerca campagne', approval: 'Approvazione', placement: 'Posizionamento', campaign: 'Campagna', scopePlacement: 'Ambito / posizionamento', scheduledBrowserTimezone: 'Programmato nel fuso orario del browser', performance: 'Prestazioni',
  noDescription: 'Nessuna descrizione', approvalPrefix: 'Approvazione: {{value}}', discountOff: '{{value}} {{unit}} di sconto', fixedDiscount: 'fisso', eventCount: 'eventi', loadingCampaigns: 'Caricamento campagne…', noCampaignsFilters: 'Nessuna campagna corrisponde a questi filtri.',
  pageLabel: 'Pagina {{page}} di {{last}}', campaignDetailsAnalyticsActions: 'Dettagli, analisi e azioni della campagna', promotionalBannerReview: 'Revisione banner promozionale', discountCampaignControl: 'Gestione campagne sconto',
  campaignReviewDescription: 'Revisiona le campagne programmate, controlla cronologia e prestazioni e gestisci il ciclo di vita in modo controllato.', datesTimezoneDescription: 'Date ed eventi di audit sono mostrati nel fuso orario del browser.',
  campaignStatusLabel: 'Stato', campaignStarts: 'Inizio', campaignEnds: 'Fine', campaignApproval: 'Approvazione', campaignDiscount: 'Sconto', cta: 'CTA', analytics: 'Analisi', orderUsage: 'Utilizzo ordini',
  auditHistory: 'Cronologia audit', auditAction: 'Azione audit', noReasonSupplied: 'Nessun motivo fornito.', campaignSchedule: 'Programmazione campagna', reasonReviewActions: 'Motivo delle azioni di revisione',
  campaignReasonPlaceholder: 'Obbligatorio per rifiuto o terminazione. Approvazione, pausa, ripresa ed eliminazione sono disponibili immediatamente.', giveRejectionReason: 'Inserisci il motivo del rifiuto per il venditore:', actionCompleted: '{{action}} completata.',
  metric_orders: 'Ordini', metric_impressions: 'Impressioni', metric_clicks: 'Clic', metric_conversions: 'Conversioni', metric_revenue: 'Ricavi', metric_views: 'Visualizzazioni',
  campaignScope_store: 'Negozio', campaignScope_product: 'Prodotto', campaignScope_category: 'Categoria', campaignScope_platform: 'Piattaforma', discountType_percentage: 'percentuale', discountType_fixed: 'fisso',
});

const translations: Record<Language, Record<string, string>> = { en, it };
const STORAGE_KEY = 'admin_language';
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function interpolate(value: string, values?: TranslationValues) {
  if (!values) return value;
  return value.replace(/\{\{(\w+)\}\}/g, (_, name: string) => String(values[name] ?? `{{${name}}}`));
}

export function statusKey(value: unknown) {
  return `status_${String(value ?? '').toLowerCase().replace(/[^a-z0-9]+/g, '_')}`;
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  useEffect(() => {
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved === 'en' || saved === 'it') {
      // The stored preference is restored after hydration so the server and client markup stay consistent.
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setLanguageState(saved);
    }
  }, []);
  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);
  const value = useMemo<LanguageContextType>(() => ({
    language,
    setLanguage: setLanguageState,
    t: (key, values) => interpolate(translations[language][key] ?? translations.en[key] ?? key, values),
  }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
}
