'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { adService, money, terminal, adError, type Campaign, type Analytics, type BudgetTransaction, type Audit, type Metric, type Page } from '@/services/ad-service';
import { useLiveRefresh } from '@/hooks/useLiveRefresh';
import { statusKey, useLanguage } from '@/contexts/LanguageContext';

function MetricsTable({ rows, dimension }: { rows: Metric[]; dimension: 'day' | 'placement' | 'location' }) {
  const { t } = useLanguage();
  return <div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr className="border-b text-slate-500">{[dimension, 'impressions', 'clicks', 'spend', 'conversions', 'revenue'].map(key => <th className="py-3 pr-4 capitalize" key={key}>{t(key)}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={String(row[dimension])} className="border-b"><td className="py-3 pr-4 capitalize">{String(row[dimension])}</td><td>{row.impressions}</td><td>{row.clicks}</td><td>{money(row.spent_cents)}</td><td>{row.conversions}</td><td>{money(row.revenue_cents)}</td></tr>)}</tbody></table>{!rows.length && <p className="py-4 text-slate-500">{t('noEvents')}</p>}</div>;
}

export default function CampaignDetails({ id, admin = false }: { id: number; admin?: boolean }) {
  const { t } = useLanguage(); const [campaign, setCampaign] = useState<Campaign | null>(null); const [analytics, setAnalytics] = useState<Analytics | null>(null); const [transactions, setTransactions] = useState<Page<BudgetTransaction> | null>(null); const [audits, setAudits] = useState<Page<Audit> | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [reason, setReason] = useState(''); const [pendingAction, setPendingAction] = useState(''); const [tab, setTab] = useState('analytics'); const [page, setPage] = useState(1); const [auditPage, setAuditPage] = useState(1);
  const label = (value?: string) => value ? t(statusKey(value)) : t('notRecorded');
  const placementLabel = (value?: string) => value ? t(`placement_${value}`) : t('unverified');
  const load = useCallback(async () => { try { const [campaignData, report, tx] = await Promise.all([adService.get(id), adService.analytics(id), adService.transactions(id, page)]); setCampaign(campaignData); setAnalytics(report); setTransactions(tx); if (admin) setAudits(await adService.audits(id, auditPage)); setError(''); } catch (requestError) { setError(adError(requestError) || t('requestFailed')); } }, [admin, auditPage, id, page, t]);
  useEffect(() => { void load(); }, [load]); useLiveRefresh(load);
  const perform = async (action: string) => { setBusy(true); setError(''); try { await adService.action(id, action, reason || undefined); setPendingAction(''); setReason(''); await load(); } catch (requestError) { setError(adError(requestError) || t('requestFailed')); } finally { setBusy(false); } };
  const base = admin ? '/ad-campaigns' : '/boost-ads';
  if (!campaign) return <div><Link href={base} className="text-blue-700">← {t('boostCampaigns')}</Link><p className="p-6" role={error ? 'alert' : 'status'}>{error || t('loading')}</p><button onClick={() => void load()}>{t('retry')}</button></div>;
  const current = analytics?.summary || campaign; const actions: string[] = [];
  if (!terminal(current.status) && current.status !== 'reconciliation_hold') { if (admin) { if (current.status === 'pending_review') actions.push('approve', 'reject'); if (current.status === 'legacy_review') actions.push('reject'); if (['active', 'scheduled'].includes(current.status)) actions.push('pause'); if (current.status === 'paused') actions.push('resume'); actions.push('terminate'); if (Number(current.remaining_cents) > 0) actions.push('refund'); } else { if (['pending_payment', 'payment_failed'].includes(current.status)) actions.push('pay'); if (['active', 'scheduled'].includes(current.status)) actions.push('pause'); if (current.status === 'paused' && current.pause_source !== 'admin') actions.push('resume'); actions.push('cancel'); } }
  const actionLabel = (value: string) => t(`action_${value}`);
  return <div className="space-y-6 text-slate-900">
    <Link href={base} className="text-blue-700">← {t('allCampaigns')}</Link>
    <div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm text-slate-500">{t('campaign')} #{current.id}{current.seller ? ` · ${current.seller.name}` : ''}</p><h1 className="text-3xl font-bold">{current.name}</h1><p className="mt-2"><span className="inline-block bg-blue-100 text-blue-900 rounded-full px-3 py-1 mr-2">{label(current.status)}</span>{t('payment')}: {label(current.payment_status)}</p></div><div className="flex flex-wrap gap-2 items-start">{actions.map(action => <button key={action} disabled={busy} className="border border-slate-300 bg-white rounded-lg px-3 py-2 disabled:opacity-50" onClick={() => { setPendingAction(action); setReason(''); }}>{actionLabel(action)}</button>)}{!admin && terminal(current.status) && <Link className="bg-blue-700 text-white px-3 py-2 rounded-lg" href={'/boost-ads?duplicate=' + current.id}>{t('duplicateCampaign')}</Link>}</div></div>
    {error && <p role="alert" className="bg-red-50 text-red-800 p-4 rounded-lg">{error}</p>}
    {pendingAction && <form className="rounded-xl border border-blue-200 bg-blue-50 p-4 space-y-3" onSubmit={event => { event.preventDefault(); void perform(pendingAction); }}><h2 className="font-semibold">{t('confirmAction', { action: actionLabel(pendingAction) })}</h2><p className="text-sm">{pendingAction === 'pay' ? `${t('reserve')} ${money(current.budget_cents)} ${t('fromWallet')}.` : ['cancel', 'reject', 'terminate', 'refund'].includes(pendingAction) ? `${t('stopDelivery')} (${money(current.remaining_cents)}).` : pendingAction === 'pause' ? t('spendingStops') : t('campaignValidation')}</p>{admin && <label className="block text-sm">{t('reasonRecorded')}<textarea required minLength={3} maxLength={2000} value={reason} onChange={event => setReason(event.target.value)} className="block border rounded-lg p-2 mt-1 w-full" /></label>}<div className="flex gap-3"><button disabled={busy} className="bg-blue-700 text-white px-4 py-2 rounded-lg">{busy ? t('processing') : t('confirmAction', { action: actionLabel(pendingAction) })}</button><button type="button" disabled={busy} onClick={() => setPendingAction('')}>{t('back')}</button></div></form>}
    {current.rejection_reason && <p className="p-4 bg-red-50 rounded-lg">{t('rejectionReason')} {current.rejection_reason}</p>}
    {current.status === 'legacy_review' && <div className="p-4 bg-amber-50 rounded-lg"><p>{t('legacyCampaignWarning')}</p>{admin && <pre className="text-xs overflow-auto mt-2">{JSON.stringify(current.legacy_snapshot, null, 2)}</pre>}</div>}
    {current.status === 'reconciliation_hold' && <p className="p-4 bg-amber-50 rounded-lg">{t('reconciliationWarning')}</p>}
    <div className="grid md:grid-cols-3 gap-4 bg-white border rounded-xl p-5"><div><p className="text-slate-500 text-sm">{t('product')}</p><p className="font-semibold">{current.product?.name || t('unavailableProduct')} (#{current.product_id})</p><p className="text-sm">{current.product ? `€${Number(current.product.price).toFixed(2)} · ${t('stock')}: ${current.product.stock_quantity} · ${current.product.is_approved ? t('approved') : t('notApproved')}` : ''}</p></div><div><p className="text-slate-500 text-sm">{t('campaignDates')}</p><p>{new Date(current.starts_at).toLocaleString()} → {new Date(current.ends_at).toLocaleString()}</p><p className="text-xs text-slate-500">{t('dailyBudgetUtc')}</p></div><div><p className="text-slate-500 text-sm">{t('targetingPlacements')}</p><p>{current.locations.join(', ') || t('unverified')}</p><p>{current.placements.map(placementLabel).join(', ') || t('unverified')}</p></div></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[[t('campaignBudget'), money(current.budget_cents)], [t('spend'), money(current.spent_cents)], [t('remainingReservation'), money(current.remaining_cents)], [t('returnedWallet'), money(current.released_cents)], [t('budgetType'), money(current.budget_amount_cents) + (current.budget_type === 'daily' ? ` / ${t('day')}` : ` ${t('total').toLowerCase()}`)], [t('cpcBid'), money(current.bid_cents)], [t('impressions'), current.impressions], [t('uniqueImpressions'), current.unique_impressions], [t('clicks'), current.clicks], ['CTR', current.ctr + '%'], [t('averageCpc'), money(current.average_cpc_cents)], [t('productViews'), current.product_views], [t('addToCarts'), current.add_to_carts], [t('conversions'), current.conversions], [t('conversionRate'), current.conversion_rate + '%'], [t('attributedRevenue'), money(current.revenue_cents)], ['ROAS', current.roas + '×']].map(([key, value]) => <div key={String(key)} className="bg-white rounded-xl border p-4"><p className="text-xs text-slate-500">{key}</p><p className="text-lg font-semibold mt-1">{value}</p></div>)}</div>
    <div className="flex gap-3 border-b">{['analytics', 'transactions', ...(admin ? ['audit'] : [])].map(value => <button type="button" key={value} onClick={() => setTab(value)} className={`px-3 py-3 capitalize ${tab === value ? 'border-b-2 border-blue-700 text-blue-700' : ''}`}>{value === 'audit' ? t('auditHistory') : t(value)}</button>)}</div>
    <div className="bg-white rounded-xl border p-5">{tab === 'analytics' && analytics && <div className="space-y-6"><p className="text-sm text-slate-500">{t('analyticsExplanation', { days: analytics.attribution_window_days })}</p><div><h2 className="font-semibold">{t('dailyPerformance')}</h2><MetricsTable rows={analytics.daily} dimension="day" /></div><div><h2 className="font-semibold">{t('byPlacement')}</h2><MetricsTable rows={analytics.placements} dimension="placement" /></div><div><h2 className="font-semibold">{t('byLocation')}</h2><MetricsTable rows={analytics.locations} dimension="location" /></div></div>}{tab === 'transactions' && <div className="overflow-auto"><table className="w-full text-sm text-left"><thead><tr>{['date', 'type', 'amount', 'reservedBalanceAfter', 'sourceBalances'].map(key => <th key={key} className="pb-3 pr-4">{t(key)}</th>)}</tr></thead><tbody>{transactions?.data.map(transaction => <tr key={transaction.id} className="border-t"><td className="py-3">{new Date(transaction.created_at).toLocaleString()}</td><td>{label(transaction.type)}</td><td>{money(transaction.amount_cents)}</td><td>{money(transaction.balance_after_cents)}</td><td className="text-xs">{JSON.stringify(transaction.metadata)}</td></tr>)}</tbody></table><div className="flex gap-4 pt-4"><button disabled={page <= 1} onClick={() => setPage(value => value - 1)}>{t('previous')}</button><span>{t('pageOf', { page, last: transactions?.last_page || 1 })}</span><button disabled={page >= (transactions?.last_page || 1)} onClick={() => setPage(value => value + 1)}>{t('next')}</button></div></div>}{tab === 'audit' && <div className="space-y-3">{audits?.data.map(audit => <div key={audit.id} className="border-b pb-3"><p className="font-medium">{label(audit.action)}: {audit.from_status ? label(audit.from_status) : t('new')} → {label(audit.to_status)}</p><p className="text-sm">{audit.reason}</p><p className="text-xs text-slate-500">{new Date(audit.created_at).toLocaleString()} · {audit.actor_id ? `${t('user')} #${audit.actor_id}` : t('system')}</p></div>)}<div className="flex gap-4"><button disabled={auditPage <= 1} onClick={() => setAuditPage(value => value - 1)}>{t('previous')}</button><span>{t('pageOf', { page: auditPage, last: audits?.last_page || 1 })}</span><button disabled={auditPage >= (audits?.last_page || 1)} onClick={() => setAuditPage(value => value + 1)}>{t('next')}</button></div></div>}</div>
  </div>;
}
