'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { adService, money, type Campaign, type Page } from '@/services/ad-service';
import { useLiveRefresh } from '@/hooks/useLiveRefresh';
import { statusKey, useLanguage } from '@/contexts/LanguageContext';

export default function CampaignList({ admin = false, refreshKey = 0 }: { admin?: boolean; refreshKey?: number }) {
  const { t } = useLanguage(); const productId = useSearchParams().get('product_id') || ''; const [rows, setRows] = useState<Page<Campaign> | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [filters, setFilters] = useState({ status: '', payment_status: '', seller_id: '', product_id: productId, from: '', to: '' }); const [applied, setApplied] = useState<Record<string, string>>(productId ? { product_id: productId } : {}); const [page, setPage] = useState(1);
  const label = (value?: string) => value ? t(statusKey(value)) : t('notRecorded');
  const load = useCallback(async () => { setLoading(true); try { setRows(await adService.list({ ...applied, page })); setError(''); } catch { setError(t('requestFailed')); } finally { setLoading(false); } }, [applied, page, t]);
  useEffect(() => { void load(); }, [load, refreshKey]); useLiveRefresh(load);
  const input = 'border border-slate-300 rounded-lg p-2 bg-white text-sm w-full';
  return <div className="space-y-4">
    <form className="grid grid-cols-2 md:grid-cols-4 gap-3 bg-white border rounded-xl p-4" onSubmit={event => { event.preventDefault(); setPage(1); setApplied(Object.fromEntries(Object.entries(filters).filter(([, value]) => value !== ''))); }}>
      <label className="text-xs text-slate-600">{t('status')}<select aria-label={t('campaignStatus')} className={input} value={filters.status} onChange={event => setFilters(f => ({ ...f, status: event.target.value }))}><option value="">{t('allStatuses')}</option>{['pending_payment', 'payment_failed', 'pending_review', 'scheduled', 'active', 'paused', 'completed', 'exhausted', 'cancelled', 'rejected', 'terminated', 'invalid', 'legacy_review', 'reconciliation_hold'].map(value => <option key={value} value={value}>{label(value)}</option>)}</select></label>
      <label className="text-xs text-slate-600">{t('payment')}<select aria-label={t('payment')} className={input} value={filters.payment_status} onChange={event => setFilters(f => ({ ...f, payment_status: event.target.value }))}><option value="">{t('allPayments')}</option>{['unpaid', 'failed', 'reserved', 'released', 'unverified'].map(value => <option key={value} value={value}>{label(value)}</option>)}</select></label>
      {admin && <label className="text-xs text-slate-600">{t('sellerId')}<input type="number" min="1" className={input} value={filters.seller_id} onChange={event => setFilters(f => ({ ...f, seller_id: event.target.value }))} /></label>}
      <label className="text-xs text-slate-600">{t('productId')}<input type="number" min="1" className={input} value={filters.product_id} onChange={event => setFilters(f => ({ ...f, product_id: event.target.value }))} /></label>
      <label className="text-xs text-slate-600">{t('startsFrom')}<input type="date" className={input} value={filters.from} onChange={event => setFilters(f => ({ ...f, from: event.target.value }))} /></label>
      <label className="text-xs text-slate-600">{t('startsThrough')}<input type="date" min={filters.from || undefined} className={input} value={filters.to} onChange={event => setFilters(f => ({ ...f, to: event.target.value }))} /></label>
      <button className="rounded-lg px-4 py-2 bg-blue-700 text-white self-end" disabled={loading}>{t('applyFilters')}</button>
    </form>
    {error && <div role="alert" className="p-4 bg-red-50 text-red-800 rounded-lg">{error} <button className="underline" onClick={() => void load()}>{t('retry')}</button></div>}
    <div className="overflow-hidden rounded-xl border bg-white"><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="bg-slate-50 text-slate-500"><tr>{[['campaignProduct', ''], ['statusPayment', ''], ['dates', ''], ['budgetRemaining', ''], ['spend', ''], ['impressions', ''], ['clicksCtr', ''], ['cpc', ''], ['conversionsRevenue', ''], ['roas', '']].map(([key]) => <th className="p-3 whitespace-nowrap" key={key}>{t(key)}</th>)}</tr></thead><tbody>{rows?.data.map(campaign => <tr key={campaign.id} className="border-t hover:bg-blue-50/30"><td className="p-3 min-w-44"><Link className="font-semibold text-blue-700 hover:underline" href={(admin ? '/ad-campaigns/' : '/boost-ads/') + campaign.id}>{campaign.name}</Link><p className="text-xs text-slate-500">{campaign.product?.name || t('unavailableProduct')}{admin && campaign.seller ? ` · ${campaign.seller.name}` : ''}</p></td><td className="p-3"><span className="bg-slate-100 rounded px-2 py-1 inline-block">{label(campaign.status)}</span><p className="text-xs mt-2">{label(campaign.payment_status)}</p></td><td className="p-3 text-xs whitespace-nowrap">{new Date(campaign.starts_at).toLocaleDateString()}<br />→ {new Date(campaign.ends_at).toLocaleDateString()}</td><td className="p-3 whitespace-nowrap">{money(campaign.budget_cents)}<p className="text-xs">{money(campaign.remaining_cents)} {t('remaining')}</p></td><td className="p-3">{money(campaign.spent_cents)}</td><td className="p-3">{campaign.impressions}</td><td className="p-3">{campaign.clicks}<p className="text-xs">{campaign.ctr}%</p></td><td className="p-3">{money(campaign.average_cpc_cents)}</td><td className="p-3">{campaign.conversions}<p className="text-xs">{money(campaign.revenue_cents)}</p></td><td className="p-3">{campaign.roas}×</td></tr>)}</tbody></table></div>{loading && !rows && <p role="status" className="p-8 text-center">{t('loading')}</p>}{rows?.data.length === 0 && <p className="p-8 text-center text-slate-500">{t('noCampaignsMatch')}</p>}</div>
    <div className="flex gap-4 justify-between items-center text-sm"><p>{t('campaignsCount', { count: rows?.total || 0 })}</p><div className="flex gap-4"><button disabled={page <= 1 || loading} onClick={() => setPage(value => value - 1)}>{t('previous')}</button><span>{t('pageOf', { page, last: rows?.last_page || 1 })}</span><button disabled={page >= (rows?.last_page || 1) || loading} onClick={() => setPage(value => value + 1)}>{t('next')}</button></div></div>
  </div>;
}
