import apiClient, { getAxiosErrorMessage } from '@/lib/api-client';

export type CouponType = 'percentage' | 'fixed_amount' | 'free_shipping';

export interface CouponCard {
  id: number;
  store_id: number;
  code: string;
  description?: string;
  discount_type: CouponType;
  discount_value: number;
  minimum_eligible_subtotal?: number | null;
  starts_at?: string | null;
  ends_at?: string | null;
  scope: 'store' | 'products' | 'categories' | 'variants';
  product_ids?: number[];
  category_ids?: number[];
  variant_ids?: number[];
}

export interface StoreCouponQuote {
  store_id: number;
  store_name: string;
  original_subtotal: string;
  automatic_campaign_discount: string;
  subtotal_after_campaigns: string;
  coupon_discount: string;
  shipping_discount: string;
  final_before_shipping: string;
  coupon: {
    id: number;
    code: string;
    eligible_subtotal: string;
    discount_amount: string;
    snapshot: Record<string, unknown>;
    affected_items: Array<Record<string, unknown>>;
  } | null;
}

export interface CouponQuote {
  stores: StoreCouponQuote[];
  original_subtotal: string;
  automatic_campaign_discount: string;
  coupon_discount: string;
  shipping_discount: string;
  final_before_shipping: string;
}

/** Retained for legacy components; data is always generated by the server cart quote. */
export interface CouponValidation {
  valid: boolean;
  coupon?: { id: number; code: string; discount_type: CouponType; discount_value: number; store_id?: number };
  discount_amount?: number;
  store_id?: number;
  quote?: CouponQuote;
  message: string;
}

const quoteFromResponse = (response: { data: { data: CouponQuote } }): CouponQuote => response.data.data;

const normaliseCodes = (couponCodes: Record<string | number, string>): Record<string | number, string> =>
  Object.fromEntries(
    Object.entries(couponCodes)
      .filter(([, value]) => typeof value === 'string' && value.trim() !== '')
      .map(([storeId, value]) => [storeId, value.trim().toUpperCase()]),
  );

export const couponService = {
  async quote(couponCodes: Record<string | number, string> = {}): Promise<CouponQuote> {
    const response = await apiClient.post('/buyer/coupons/quote', { coupon_codes: normaliseCodes(couponCodes) });
    return quoteFromResponse(response);
  },

  /** `orderTotal` remains optional only for callers not yet upgraded; it is deliberately ignored. */
  async validate(code: string, _orderTotal?: number, storeId?: number, existingCodes: Record<string | number, string> = {}): Promise<CouponValidation> {
    try {
      const normalizedCode = code.trim().toUpperCase();
      if (!normalizedCode) return { valid: false, message: 'Enter a coupon code.' };

      // Resolve the code first.  This gives the server the opportunity to
      // verify ownership and real-cart eligibility before the code is merged
      // with coupons selected for other sellers.
      const response = await apiClient.post('/buyer/coupons/apply', {
        code: normalizedCode,
        ...(storeId ? { store_id: storeId } : {}),
      });
      let quote = quoteFromResponse(response);
      let store = quote.stores.find((entry) => entry.coupon?.code.toUpperCase() === normalizedCode);

      // A multi-store checkout must send an explicit store => code map.  The
      // old `_single` key was ambiguous once another store already had a
      // coupon selected and led to valid codes being reported as invalid.
      if (store?.store_id && Object.keys(existingCodes).length) {
        quote = await this.quote({
          ...normaliseCodes(existingCodes),
          [store.store_id]: normalizedCode,
        });
        store = quote.stores.find((entry) => entry.store_id === store?.store_id);
      }

      if (!store?.coupon) {
        return { valid: false, message: 'This coupon does not apply to the current cart.' };
      }
      const snapshot = store?.coupon?.snapshot || {};
      return {
        valid: true,
        coupon: {
          id: store.coupon.id,
          code: store.coupon.code,
          discount_type: snapshot.discount_type as CouponType,
          discount_value: Number(snapshot.discount_value || 0),
          store_id: store.store_id,
        },
        store_id: store.store_id,
        discount_amount: Number(store.coupon.discount_amount || 0),
        quote,
        message: 'Coupon quote calculated successfully.',
      };
    } catch (error: unknown) {
      return { valid: false, message: getAxiosErrorMessage(error) };
    }
  },

  async remove(): Promise<CouponQuote> {
    const response = await apiClient.post('/buyer/coupons/remove');
    return quoteFromResponse(response);
  },

  async getStoreCoupons(storeId: number): Promise<CouponCard[]> {
    const response = await apiClient.get(`/buyer/coupons/stores/${storeId}`);
    return response.data.data;
  },
  async getProductCoupons(productId: number): Promise<CouponCard[]> {
    const response = await apiClient.get(`/buyer/coupons/products/${productId}`);
    return response.data.data;
  },
  async getCategoryCoupons(categoryId: number): Promise<CouponCard[]> {
    const response = await apiClient.get(`/buyer/coupons/categories/${categoryId}`);
    return response.data.data;
  },
};
