'use client';

import { useCallback, useEffect, useState } from 'react';
import AdminLayout from '@/components/layout/AdminLayout';
import { referralService, type ReferralCampaign, type ReferralReward, type ReferralSettings } from '@/services/referral-service';
import { useLiveRefresh } from '@/hooks/useLiveRefresh';
import { statusKey, useLanguage } from '@/contexts/LanguageContext';

const euro = (value: unknown) => `€${Number(value || 0).toFixed(2)}`;
type Tab = 'overview' | 'campaigns' | 'rewards' | 'audit';
type AuditLog = { id: number; action: string; reason?: string | null; created_at: string; actor?: { email?: string }; reward?: { id: number }; campaign?: { name: string } };
const errorMessage = (error: unknown, fallback: string) => { if (typeof error === 'object' && error && 'response' in error) return (error as { response?: { data?: { message?: string } } }).response?.data?.message || fallback; return fallback; };

export default function AdminReferralsPage() {
  const { t } = useLanguage(); const [tab, setTab] = useState<Tab>('overview'); const [settings, setSettings] = useState<ReferralSettings>({}); const [campaigns, setCampaigns] = useState<ReferralCampaign[]>([]); const [rewards, setRewards] = useState<ReferralReward[]>([]); const [audit, setAudit] = useState<AuditLog[]>([]); const [status, setStatus] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const [settingsResponse, campaignResponse, rewardResponse, auditResponse] = await Promise.all([referralService.settings(), referralService.campaigns(), referralService.rewards(status ? { status } : undefined), referralService.audit()]); setSettings(settingsResponse); setCampaigns(campaignResponse.data || []); setRewards(rewardResponse.data || []); setAudit(auditResponse.data || []); setError(''); } catch (requestError) { setError(errorMessage(requestError, t('unableLoadReferrals'))); } }, [status, t]);
  useLiveRefresh(load); useEffect(() => { void load(); }, [load]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { setSettings(await referralService.updateSettings(settings)); } catch (requestError) { setError(errorMessage(requestError, t('couldNotSaveReferral'))); } finally { setSaving(false); } };
  const campaignAction = async (row: ReferralCampaign, action: 'approve' | 'reject' | 'suspend' | 'archive') => { const reason = action === 'approve' || action === 'archive' ? undefined : window.prompt(`${t('reasonForAction')} ${t('sellerReferralCampaign').toLowerCase()} “${row.name}”`); if (action !== 'approve' && action !== 'archive' && !reason) return; try { await referralService.campaignAction(row.id, action, reason || undefined); await load(); } catch (requestError) { setError(errorMessage(requestError, t('actionFailed'))); } };
  const rewardAction = async (row: ReferralReward, action: 'approve' | 'reject' | 'suspend' | 'reverse') => { const reason = window.prompt(`${t('reasonForAction')} ${t('reward').toLowerCase()} #${row.id}`); if (!reason) return; try { await referralService.rewardAction(row.id, action, reason); await load(); } catch (requestError) { setError(errorMessage(requestError, t('actionFailed'))); } };
  const exportReport = async () => { try { const blob = await referralService.exportFinancialReport(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'referral-financial-report.csv'; link.click(); URL.revokeObjectURL(url); } catch (requestError) { setError(errorMessage(requestError, t('couldNotExportReferral'))); } };
  const tabLabels: Record<Tab, string> = { overview: t('referralOverview'), campaigns: t('referralCampaigns'), rewards: t('referralRewards'), audit: t('referralAudit') };
  return <AdminLayout><div className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-3xl font-bold">{t('referralProgram')}</h1><p className="mt-2 text-gray-600">{t('referralDescription')}</p></div><button type="button" onClick={() => void exportReport()} className="rounded-lg border px-4 py-2 text-sm">{t('exportFinancialReport')}</button></header>
    {error && <p role="alert" className="rounded-lg bg-red-50 p-4 text-red-700">{error}</p>}
    <nav className="flex flex-wrap gap-2" aria-label={t('referralProgram')}>{(Object.keys(tabLabels) as Tab[]).map(item => <button type="button" key={item} onClick={() => setTab(item)} className={`rounded-lg px-4 py-2 ${tab === item ? 'bg-blue-700 text-white' : 'border bg-white'}`}>{tabLabels[item]}</button>)}</nav>
    {tab === 'overview' && <SettingsForm settings={settings} setSettings={setSettings} save={save} saving={saving} />}
    {tab === 'campaigns' && <Campaigns rows={campaigns} action={campaignAction} />}
    {tab === 'rewards' && <Rewards rows={rewards} status={status} setStatus={setStatus} action={rewardAction} />}
    {tab === 'audit' && <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">{t('referralAuditLog')}</h2><div className="mt-4 space-y-3">{audit.map(row => <div key={row.id} className="rounded border p-3 text-sm"><p className="font-medium">{t(`referralAction_${row.action}`)} {row.reward && `· ${t('reward')} #${row.reward.id}`} {row.campaign && `· ${row.campaign.name}`}</p><p className="text-gray-600">{row.reason || t('noReason')} · {row.actor?.email || t('admin')} · {new Date(row.created_at).toLocaleString()}</p></div>)}{!audit.length && <p className="text-sm text-gray-500">{t('noReferralAudit')}</p>}</div></section>}
  </div></AdminLayout>;
}

function SettingsForm({ settings, setSettings, save, saving }: { settings: ReferralSettings; setSettings: React.Dispatch<React.SetStateAction<ReferralSettings>>; save: (event: React.FormEvent) => void; saving: boolean }) {
  const { t } = useLanguage();
  const bool = (key: string, label: string) => <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(settings[key])} onChange={event => setSettings(previous => ({ ...previous, [key]: event.target.checked }))} />{label}</label>;
  const number = (key: string, label: string, step = '1') => <label className="block text-sm font-medium">{label}<input type="number" min="0" step={step} value={String(settings[key] ?? '')} onChange={event => setSettings(previous => ({ ...previous, [key]: event.target.value === '' ? null : Number(event.target.value) }))} className="mt-1 block w-full rounded border p-2" /></label>;
  return <form onSubmit={save} className="space-y-6 rounded-xl border bg-white p-6"><div><h2 className="text-xl font-bold">{t('platformReferralSettings')}</h2><p className="mt-1 text-sm text-gray-600">{t('referralSettingsDescription')}</p></div><div className="grid gap-4 md:grid-cols-2">{bool('platform_referrals_enabled', t('enablePlatformReferral'))}{bool('seller_referrals_require_approval', t('requireSellerApproval'))}{bool('seller_referrals_allow_existing_buyers', t('allowExistingBuyers'))}{bool('referral_allow_platform_stacking', t('allowStacking'))}{bool('referral_require_email_verification', t('requireEmail'))}{bool('referral_require_phone_verification', t('requirePhone'))}<label className="block text-sm font-medium">{t('rewardType')}<select value={String(settings.platform_referral_reward_type || 'fixed')} onChange={event => setSettings(previous => ({ ...previous, platform_referral_reward_type: event.target.value }))} className="mt-1 block w-full rounded border p-2"><option value="fixed">{t('fixedEur')}</option><option value="percentage">{t('percentage')}</option></select></label>{number('platform_referral_reward_amount', t('rewardAmount'), '0.01')}{number('platform_referral_max_reward_per_order', t('maxReward'), '0.01')}{number('platform_referral_minimum_order_amount', t('minOrder'), '0.01')}{number('referral_attribution_days', t('attributionDays'))}{number('referral_reward_waiting_days', t('waitingDays'))}{number('platform_referral_monthly_reward_limit', t('monthlyLimit'))}{number('platform_referral_per_buyer_limit', t('buyerLimit'))}</div><button disabled={saving} className="rounded-lg bg-blue-700 px-5 py-3 font-medium text-white disabled:opacity-50">{saving ? t('saving') : t('saveReferralSettings')}</button></form>;
}

function Campaigns({ rows, action }: { rows: ReferralCampaign[]; action: (row: ReferralCampaign, action: 'approve' | 'reject' | 'suspend' | 'archive') => void }) {
  const { t } = useLanguage();
  return <section className="space-y-4">{rows.map(row => <article key={row.id} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">{row.name} <span className="text-sm font-normal text-gray-500">{row.identifier}</span></h2><p className="text-sm text-gray-600">{row.store?.name} · {row.seller?.email} · {t(statusKey(row.status))} / {t(statusKey(row.approval_status))}</p></div><p className="font-semibold">{euro(row.budget_spent)} {t('paid')} / {euro(row.budget_reserved)} {t('reserved')}</p></div>{row.analytics && <p className="mt-3 text-sm text-gray-600">{row.analytics.clicks} {t('clicks')} · {row.analytics.orders} {t('orders').toLowerCase()} · {euro(row.analytics.revenue_generated)} {t('totalRevenue').toLowerCase()} · {euro(row.analytics.referral_commission_cost)} {t('commission')}</p>}<div className="mt-4 flex flex-wrap gap-2">{row.approval_status === 'pending' && <button type="button" onClick={() => void action(row, 'approve')} className="rounded bg-green-700 px-3 py-2 text-sm text-white">{t('approve')}</button>}<button type="button" onClick={() => void action(row, 'suspend')} className="rounded border px-3 py-2 text-sm">{t('suspend')}</button><button type="button" onClick={() => void action(row, 'reject')} className="rounded border border-red-200 px-3 py-2 text-sm text-red-700">{t('reject')}</button></div></article>)}{!rows.length && <p className="rounded-xl border bg-white p-6 text-gray-500">{t('noCampaigns')}</p>}</section>;
}

function Rewards({ rows, status, setStatus, action }: { rows: ReferralReward[]; status: string; setStatus: (value: string) => void; action: (row: ReferralReward, action: 'approve' | 'reject' | 'suspend' | 'reverse') => void }) {
  const { t } = useLanguage();
  return <section><label className="mb-4 block text-sm">{t('filterStatus')} <select value={status} onChange={event => setStatus(event.target.value)} className="ml-2 rounded border p-2"><option value="">{t('all')}</option>{['pending', 'qualified', 'rewarded', 'rejected', 'suspended', 'reversed'].map(value => <option key={value}>{t(statusKey(value))}</option>)}</select></label><div className="space-y-4">{rows.map(row => <article key={row.id} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">{t('reward')} #{row.id} · {t(`referralSource_${row.source}`)} · {t(statusKey(row.status))}</h2><p className="text-sm text-gray-600">{row.referrer?.email} → {row.referred?.email} · {row.campaign?.name || t('platform')} · {t('order')} {row.order?.order_no || '—'}</p></div><strong>{euro(row.amount)}</strong></div><p className="mt-2 text-sm text-gray-600">{t('eligibleSubtotal')} {euro(row.eligible_subtotal)} {row.reason ? `· ${row.reason}` : ''}</p><p className="mt-2 text-xs text-gray-500">{t('trace')}: {t('buyerTransaction')} #{row.buyer_transaction?.id || '—'} · {t('sellerLedger')} #{row.seller_wallet_entry?.id || '—'} · {t('platformLedger')} #{row.platform_ledger_entry?.id || '—'} {row.reversal ? `· ${t('reversal')} #${row.reversal.id}` : ''}</p><div className="mt-4 flex flex-wrap gap-2">{['pending', 'suspended'].includes(row.status) && <button type="button" onClick={() => void action(row, 'approve')} className="rounded bg-green-700 px-3 py-2 text-sm text-white">{t('manualApprove')}</button>}{['pending', 'qualified', 'suspended'].includes(row.status) && <><button type="button" onClick={() => void action(row, 'suspend')} className="rounded border px-3 py-2 text-sm">{t('suspend')}</button><button type="button" onClick={() => void action(row, 'reject')} className="rounded border border-red-200 px-3 py-2 text-sm text-red-700">{t('reject')}</button></>}{row.status === 'rewarded' && <button type="button" onClick={() => void action(row, 'reverse')} className="rounded border border-red-200 px-3 py-2 text-sm text-red-700">{t('reverse')}</button>}</div></article>)}{!rows.length && <p className="rounded-xl border bg-white p-6 text-gray-500">{t('noRewards')}</p>}</div></section>;
}
